### ISSUE TITLE
Secure Speech Service Key/Region

### ISSUE THREAD

**Issue by hunterjam** [Azure-Samples/chat-with-your-data-solution-accelerator#101]
# Motivation

Ensure sensitive credentials cannot be exposed. We are currently returning the Azure Speech Key from the `/api/config` endpoint in plain text https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/ede0d6d93abd38c1b7b071ebf96ad18a3098b457/code/app.py#L32-L40

# How would you feel if this feature request was implemented?

![secure](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYzc3Y2QzMzBwYnVybWhuZG9yOWJibnNtY2Uza3Z0M24zZjN2NGJqOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/X68QCGb5qx596/giphy-downsized-large.gif)

# Requirements

- Stop returning the value of the Azure Speech Key from the `/api/config` endpoint. Consider using `SecretStr` from pydantic https://docs.pydantic.dev/2.6/examples/secrets/ to return a masked version of the secret
- Ensure that the speech service from the frontend is still functional (it calls the `/api/config` endpoint) #501 
- **Stretch:** Improve this endpoint to return the full config with all secrets masked

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Implement https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/README.md#token-exchange-process
- [x] #683

**Comment by adamdougal** [comment]
> The solution now has KeyVault - should this be utilised?

Looks like we are now using Key Vault. I think this is more that the key is returned in plain text from the `/api/config` end point 😬https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/ede0d6d93abd38c1b7b071ebf96ad18a3098b457/code/app.py#L37

I'll reword the issue to be clearer.

**Comment by superhindupur** [comment]
https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/js/browser/README.md#token-exchange-process can be relevant for this task

**Comment by cecheta** [comment]
After discussing with the team, it has been decided to remove the `/api/config` endpoint entirely, as there is on requirement for the endpoint, and to have the endpoint while also masking secrets is non-trivial.

If such a requirement arises, the endpoint may be added back to the application.
