### ISSUE TITLE
Cannot run azd auth login in devcontainer

### ISSUE THREAD

**Issue by rmthurman** [Azure-Samples/chat-with-your-data-solution-accelerator#1023]
# Describe the bug
I get this error when trying to run azd auth login in devcontainer:
azd auth login
/usr/bin/xdg-open: 882: www-browser: not found
/usr/bin/xdg-open: 882: links2: not found
/usr/bin/xdg-open: 882: elinks: not found
/usr/bin/xdg-open: 882: links: not found
/usr/bin/xdg-open: 882: lynx: not found
/usr/bin/xdg-open: 882: w3m: not found
xdg-open: no method available for opening ...

# Expected behavior

# How does this bug make you feel?
![gif](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXAxM2swOHl2eW5kY2pudG9uODMwbGhjbDlua2tyb2VmbXV2Z3R1bSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/F3BeiZNq6VbDwyxzxF/giphy.gif)

---

# Debugging information

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
Hi @rmthurman - could it be that port 882 is being used by something else. When you try and login, it is trying to open a browser window to log you in

**Comment by ross-p-smith** [comment]
I think we got past this now? Shall we close?
