### ISSUE TITLE
Requesting Support of PowerPoint file types

### ISSUE THREAD

**Issue by mattGLB** [Azure-Samples/chat-with-your-data-solution-accelerator#106]
Requesting support of PowerPoint file type, currently only following file types:

PDF
JPEG
JPG
PNG
TXT
HTML
MD (Markdown)
DOCX

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by komalg1** [comment]
This feature requires a change to add python package azure-ai-documentintelligence to use DocumentIntelligenceClient instead of DocumentAnalysisClient. Holding off the change temporarily as it can have an impact on the currently deployed versions.

**Comment by komalg1** [comment]
Document Intelligence resource (formally known as Azure Form Recognizer) is currently only available in 'EastUs', 'WestUS2' & 'WestEurope'
[Azure AI Document Intelligence](https://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/overview?view=doc-intel-4.0.0)
