### ISSUE TITLE
The AZURE_OPENAI_SYSTEM_MESSAGE keeps reseting

### ISSUE THREAD

**Issue by djseng** [Azure-Samples/chat-with-your-data-solution-accelerator#1066]
# Describe the bug
When I set the `AZURE_OPENAI_SYSTEM_MESSAGE` then do an `azd up` the system message isn't set as expected.

# Expected behavior
I'd expect the `AZURE_OPENAI_SYSTEM_MESSAGE` to be set, and used in the function app.

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
```
azd env refresh
azd set AZURE_OPENAI_SYSTEM_MESSAGE "You help people find information."
azd up
```

ssh to the function app
```
echo $AZURE_OPENAI_SYSTEM_MESSAGE
```
outputs nothing.

I also tried
```
azd env refresh
azd set AZURE_OPENAI_SYSTEM_MESSAGE "You help people find information."
azd deploy function
```

ssh to the function app
```
echo $AZURE_OPENAI_SYSTEM_MESSAGE
```
outputs nothing

## Work Around
If I manually add a new AZURE_OPENAI_SYSTEM_MESSAGE environment variable then I see the expected SYSTEM_MESSAGE.

ssh to the function app
```
echo $AZURE_OPENAI_SYSTEM_MESSAGE
```
outputs the expected system message
---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Prasanjeet-Microsoft** [comment]
Hello @djseng, can you please confirm whether we need to reproduce this steps in dev container platform or somewhere else?

**Comment by djseng** [comment]
@Prasanjeet-Microsoft this is when deploying to azure.

**Comment by Prasanjeet-Microsoft** [comment]
@djseng We have tried to reproduce the steps that is mentioned above. But it seems "set" is not a valid azd command to set the value of environment variable. Therefore, we have tried to find the alternate way to set the value of environment variables. Please find below commands that we have come across which is working fine:

1. Ensure Azure CLI is Installed and Logged In
- Make sure you have Azure CLI installed and authenticated (az login).

2. Run the Azure CLI Command
- Use the az webapp config appsettings set command to set the environment variable for your Azure Web App:

az webapp config appsettings set --resource-group YourResourceGroupName --name YourWebAppName --settings AZURE_OPENAI_SYSTEM_MESSAGE="You help people find information."

Replace:
- YourResourceGroupName with the actual name of your resource group.
- YourWebAppName with the actual name of your Azure Web App.

This command sets the environment variable AZURE_OPENAI_SYSTEM_MESSAGE with the value "You help people find information." for your specified Azure Web App.

3. Verify the Setting
- After running the command, you can verify the environment variable setting using:

az webapp config appsettings list --resource-group YourResourceGroupName --name YourWebAppName --query "[?name=='AZURE_OPENAI_SYSTEM_MESSAGE'].[value]" --output table

This command lists the app settings (environment variables) for your Azure Web App YourWebAppName in YourResourceGroupName and filters specifically for AZURE_OPENAI_SYSTEM_MESSAGE.

FYI @Roopan-Microsoft

**Comment by djseng** [comment]
@Prasanjeet-Microsoft  `azd` (Azure Developer CLI) is _not_ `az` (Azure CLI) ... `azd` is used heavily in this project's documentation to deploy and set environment variables for this project.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @djseng , This is to inform you that we have identified the root cause of this issue and got to know that AZURE_OPENAI_SYSTEM_MESSAGE environment variable param was missing in main.bicepparam file due to which value of AZURE_OPENAI_SYSTEM_MESSAGE env variable was getting reset every time after running the azd up command . 

We also wanted to inform that we are not passing AZURE_OPENAI_SYSTEM_MESSAGE environment variable param in the function app appSettings in main.bicep file. We are passing this param only in app service (webapp and admin webapp). Do you want this param (AZURE_OPENAI_SYSTEM_MESSAGE) to be added in function app also?

**Comment by djseng** [comment]
@Prasanjeet-Microsoft my understanding of the code is that function app is what references this env variable. It makes sense to me that it should be passed to the function app from the main.bicepparam.

**Comment by Roopan-Microsoft** [comment]
@djseng - Yes, its should be passed from main.bicepparam and we found that below 2 env variables were missing 
- AZURE_OPENAI_SYSTEM_MESSAGE 
- AZURE_SEARCH_TOP_K

We have added that now and it is getting reflected when we try 
- azd env set
- azd up

**_but our query is whether to add AZURE_OPENAI_SYSTEM_MESSAGE environment variables in the function app?_**

<img width="316" alt="image" src="https://github.com/user-attachments/assets/d2344842-36fd-4832-9a7c-67d2eef43234">

**Comment by djseng** [comment]
@Roopan-Microsoft _I_ say yes. _I_ just don't think it's my call to make.

**Comment by Roopan-Microsoft** [comment]
@djseng Understood! We'll implement the changes and keep you posted.

**Comment by Prasanjeet-Microsoft** [comment]
@djseng We have made the code changes and raised the PR which has been reviewed and approved by Adam. This issue is fixed. so, can we close this issue now?

Please find below PR link for your reference:
https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1147

**Comment by djseng** [comment]
Thank you very much @Prasanjeet-Microsoft
