### ISSUE TITLE
Using Azure MySQL data

### ISSUE THREAD

**Issue by medhabhatt** [Azure-Samples/chat-with-your-data-solution-accelerator#1071]
Hi,

Instead of using documents, we want to use our enterprise data stored in Azure MySQL Flexi server DB.   Is there any tutorial which describes how to utilize that as a data source for building our own chat interface using Azure AI Hub?

**Comment by ross-p-smith** [comment]
Hi @medhabhatt - this repository is a baseline RAG implementation and as such concentrates on documents in Blob Storage. Does this help? https://learn.microsoft.com/en-us/azure/search/search-howto-connecting-azure-sql-database-to-azure-search-using-indexers

**Comment by Roopan-Microsoft** [comment]
Hi @medhabhatt - Let us know if you still face any issues or we are good to close this issue?

**Comment by Roopan-Microsoft** [comment]
@medhabhatt - Please feel free to reach out to us in case of any issue. Closing this issue for now.
