### ISSUE TITLE
Reference X not showing up when X>=2, in web app

### ISSUE THREAD

**Issue by cherifbenham** [Azure-Samples/chat-with-your-data-solution-accelerator#1072]
# Describe the bug
The answer object sometimes does not display all the used sources (clickable) to generate the answers.

# Expected behavior
The answer should contain all the references of the retrieved sources - see screenshot below

# How does this bug make you feel?

---

# Debugging information

## Screenshots
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/99403039/4e077170-cbce-4ebc-b658-c67324c07eb8)

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by adamdougal** [comment]
Heya @cherifbenham, I'm not sure I understand the issue. From the screenshot, it looks like it's retrieved all of the data from one reference correctly. Could you explain a bit more? Thanks

**Comment by cherifbenham** [comment]
Thanks @adamdougal Adam for your reactivity

The issue is that one could expect that since the generated answer mentions 2 candidate sources, it should also return 2 clickable URLs but it is not the case: 2 candidate docs are cited in the answer but only one reference URL is displayed as ref

Does it make more sense?

**Comment by adamdougal** [comment]
Gotcha! That's an odd one. Can you see the reference documents being returned in the logs of the backend application? Are they both there? It could be that the OpenAI System prompt needs tweaking.

**Comment by Roopan-Microsoft** [comment]
Hey @cherifbenham - Could you please re-test this and let us know if the issue persists?

**Comment by Roopan-Microsoft** [comment]
Closing this issue since we haven't received any updates from the user.

Hey @cherifbenham, feel free to reopen it if you continue to experience the issue.

Happy to Help!
