### ISSUE TITLE
Files ingested in Blob storage are NOT indexed in Search engine

### ISSUE THREAD

**Issue by nh-lh** [Azure-Samples/chat-with-your-data-solution-accelerator#1087]
Re-opening #284 as I am facing the same issue. Fresh deployment from the current main repository using azd-up. Batch-uploaded 15 files. The first 10 succeeded, the last 5 never appeared in the index.

`Exception while executing function: Functions.batch_push_results Result: Failure Exception: RateLimitError: Error code: 429 - {'error': {'code': '429', 'message': 'Requests to the Embeddings_Create Operation under Azure OpenAI API version 2024-02-01 have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 1 second. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.'}}`

After this error occurred, I increased the TPM rate from 30 to 60 for the gpt-3 and ada-002 deployment. Now, the exception doesn't appear anymore, but the files that are appearing in "Delete Files" / Blob are still not being indexed ...

**Comment by nh-lh** [comment]
@ross-p-smith tagging you as you were involved in the previous issue. Would be happy to contribute any further potentially useful logs

**Comment by nh-lh** [comment]
I tried many times to delete them and re-upload. Only some files are affected, but no exception appears in Azure transaction logs. Tagging in Azure storage is not related to it. I also checked and it seems the tag is set, but in which part of the code is it actually used? I only see that it's written.

 Maybe it's due to hidden errors from Document Intelligence?

**Comment by Prasanjeet-Microsoft** [comment]
@ross-p-smith @nh-lh After doing the code analysis, we identified that there is one functionality in Explore_Data.py file in which we are calling **get_unique_files** function and inside this function we are calling **get_facets()** function which will provide only top 10 facets because for each faceted navigation tree, there's a default limit of the top 10 facets. Please find below screenshots for your reference:

<img width="728" alt="image" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/169636624/ed31f946-577f-4516-be28-114bb7c0a8a9">

**Comment by Prasanjeet-Microsoft** [comment]
> Thank you for the feedback @Prasanjeet-Microsoft . I can confirm that get_facets() is the root issue and it is an Admin interface bug

Now we have found the alternate solution with minimal impact to the existing code base. Please find below screenshot for your reference:

<img width="496" alt="image" src="https://github.com/user-attachments/assets/6afc79e8-e886-45a3-9cf3-332e72b6a8a5">

<img width="514" alt="image" src="https://github.com/user-attachments/assets/3e366c7f-c6d1-4c67-ac15-225b720b19ee">

**Comment by Prasanjeet-Microsoft** [comment]
@nh-lh We have made the code changes and raised the PR which has been reviewed and approved by Adam. Now this issue is fixed so can we close this issue now?  

Please find below PR link for your reference:
https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1128

**Comment by nh-lh** [comment]
Yes that’s good!
