### ISSUE TITLE
AZURE_SEARCH_TOP_K is always 5 even when set to 15 manually

### ISSUE THREAD

**Issue by zihuq-msft** [Azure-Samples/chat-with-your-data-solution-accelerator#1109]
# Describe the bug
Created a new environment and set AZURE_SEARCH_TOP_K to 15 (tried both as integer and string) and it always comes back as 5 after azd up when building new rg/resources.

# Expected behavior
AZURE_SEARCH_TOP_K shouldn't be reset to 5 if already set in .env to 15

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. azd env set AZURE_SEARCH_TOP_K 15
2. azd up
3. azd env refresh

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Roopan-Microsoft** [comment]
@zihuq-msft  - Can you please post the screenshot of the error; it will be helpful to investigate more.

**Comment by Prasanjeet-Microsoft** [comment]
@zihuq-msft Can you please share the screenshot of the error along with the commands that you are using to check/verify the value of environment variable?

**Comment by Prasanjeet-Microsoft** [comment]
@zihuq-msft Can you please provide the screenshot of the error along with the commands that you are using to verify the value of environment variable?

**Comment by Prasanjeet-Microsoft** [comment]
@zihuq-msft We have made the code changes and raised the PR which has been reviewed and approved by Adam. This issue is fixed, so can we close this issue now?

Please find below PR link for your reference:
https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1146

**Comment by Prasanjeet-Microsoft** [comment]
@zihuq-msft We are closing this issue now since it has already been fixed. Please feel free to reopen it if you encounter any further issues.
