### ISSUE TITLE
Unable to deploy to Azure

### ISSUE THREAD

**Issue by redowl3** [Azure-Samples/chat-with-your-data-solution-accelerator#1125]
When trying to deploy to Azure we always get the following issue

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/16084017/f87b04ea-5882-4aec-bcd0-04fd48809661)

1. Click Deploy to Azure

{"code":"BadRequest","message":"Encountered an error (InternalServerError) from host runtime.","details":[{"message":"Encountered an error (InternalServerError) from host runtime."},{"code":"BadRequest"},{}]}

**Comment by Roopan-Microsoft** [comment]
@redowl3 - Could you kindly share the results after attempting deployment again? We've successfully deployed from our side. Please give it another try from your end

**Comment by redowl3** [comment]
Hi, after a number of attempts we have finally got this to work, thanks for getting back to me.
