### ISSUE TITLE
Issues with reading PNG and JPG files

### ISSUE THREAD

**Issue by veronicahorgan** [Azure-Samples/chat-with-your-data-solution-accelerator#1129]
I recently deployed Chat with Your Data and have been uploading various file types to the Admin UI. I'm encountering challenges with PNG, JPEG and MD files. Some are being ingested successfully, others are not, despite all containing text. For instance, I saved a file as both .PNG and .JPG. The .JPG file uploads without issue, but the .PNG file does not. Although all files appear in the storage account, those that are not working do not show up in the "explore data" dropdown, and I can't retrieve any information from them. All the images I tested are read correctly in document intelligence studio. Additionally, I can upload an MD file without any errors, but it too does not appear in the "explore data" dropdown.

**Comment by ross-p-smith** [comment]
Hi @veronicahorgan - As part of the deployment, there is an Azure Workbook. Were any errors displayed on any of the tabs?

**Comment by Roopan-Microsoft** [comment]
Hi @veronicahorgan - We have fixed as part of 1170 & 1172. Please retry and let us know if any issue. Thanks

**Comment by Roopan-Microsoft** [comment]
Closing this issue.
