### ISSUE TITLE
Issue with prompt response in different languages other than English

### ISSUE THREAD

**Issue by dineshkbsiemens** [Azure-Samples/chat-with-your-data-solution-accelerator#1132]
# Describe the bug
When we ask generic questions like "Hi", "Who are you?" then the response is given is different languages each time other than English.

# Expected behavior
When a question asked in English the expected response should be in English.

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. Go to 'Chat URL'
2. Ask Questions like 'Hi' or 'Who are you?'
3. Response given in different languages.
4. See attached screenshot

## Screenshots
![doc-upload-error](https://github.com/user-attachments/assets/a2f7be9c-1d72-4348-bf49-3310c7c6e1b4)

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Roopan-Microsoft** [comment]
@dineshkbsiemens - This is fixed as part of #1148. Please feel free to re-open the issue if you still face

<img width="594" alt="image" src="https://github.com/user-attachments/assets/3f63e6ec-bfe9-4dfe-800d-09c4f84b376b">
