### ISSUE TITLE
use 1Click to deploy from Azure git repo

### ISSUE THREAD

**Issue by dhaksr** [Azure-Samples/chat-with-your-data-solution-accelerator#1142]
# Motivation

I would like to deploy 1 click change based on local copy of the git repo. this will enable customization and faster adoption of the repo in projects.

# How would you feel if this feature request was implemented?

:-)

# Requirements
I make a local copy into Azure git repo (private) and make changes. I would like the 1 click deploy to pick from there. So I created Template spec using the 
<<root>>\code\infra\main.json

i want to change it to point to local azure git repo. However when we give that its giving an error in access.
I would like you to update documentation to include steps for how to make local copy and deploy using 1 click option

A list of requirements to consider this feature delivered
Custom templates
rapid and iterative deployments
- ...

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1  Update documentation
- [ ] Task 2 How to release only  changes in code fast
- [ ] ...

**Comment by ross-p-smith** [comment]
Hi there, if you would like quick and rapid deployments from your local machine, you should clone the repo and use the DevContainer, you would then use `azd up` to deploy this solution straight to Azure. The "Deploy to Azure" is a convenience for those that dont want to clone the repo. 

Cloning and using `azd auth login` and then `azd up` is the right way to go

**Comment by dhaksr** [comment]
> Hi there, if you would like quick and rapid deployments from your local machine, you should clone the repo and use the DevContainer, you would then use `azd up` to deploy this solution straight to Azure. The "Deploy to Azure" is a convenience for those that dont want to clone the repo.
> 
> Cloning and using `azd auth login` and then `azd up` is the right way to go

The problem is we hit lot of corporate firewall issues whereas one click goes thru smoothly. Hence the request for referring to azure git repo from 1-click deploy

**Comment by ross-p-smith** [comment]
In order to do what you ask, you would have to carry out these steps (unless I have misunderstood).
1) Amend the build task in your repository to build and push the docker images to your container registry
2) Amend the bicep/arm to pull the images from your container registry
3) Amend the "Deploy To Azure" button to work from your main.json

**Comment by ross-p-smith** [comment]
Hi @dhaksr - can we close this issue now?

**Comment by dhaksr** [comment]
Yes pl
