### ISSUE TITLE
In the admin web page, explore data doesnt scroll and list all files

### ISSUE THREAD

**Issue by dhaksr** [Azure-Samples/chat-with-your-data-solution-accelerator#1145]
# Describe the bug
When there are upload multiple files (say 20 files) then the explore data option shows only the first 10 files in drop down file list. If you go to the delete data option then all 20 files are listed.

In the explore data option - you can type over the file name. However there are inconsistencies in that it doesnt pick all files listed by delete data option. I have not been able to fix a pattern for this.

# Expected behavior
The file name drop down in Explore data option should list all files that are uploaded and allow users to choose the file.

# How does this bug make you feel?
:-(

---

# Debugging information

## Steps to reproduce
1. Ingest data
2. Upload more than 10 files. In our case we have 52 files uploaded
3. Go to Explore data option
4. Select the drop down in the select your file option. it should show all file names

.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Roopan-Microsoft** [comment]
Hi @dhaksr - We have provided the fix and merged. you can try re-deploying and check and confirm.

PR - https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1128

**Comment by Prasanjeet-Microsoft** [comment]
@dhaksr We are closing this issue now since it has already been fixed. Please feel free to reopen it if you encounter any further issues.
