### ISSUE TITLE
Backend (Function App) Error - Encountered an error (ServiceUnavailable) from host runtime.

### ISSUE THREAD

**Issue by yaowilli** [Azure-Samples/chat-with-your-data-solution-accelerator#1232]
# Describe the bug
Backend (Function App ) following functions and features are not loading 
 1- "add_url_embeddings | batch_push_result Code + Test" Error while loading with the message: "Your app is currently in read only mode because you are running from a package file. To make any changes update the content in your zip file and WEBSITE_RUN_FROM_PACKAGE app setting." 
    I have tried setting WEBSITE_RUN_FROM_PACKAGE == 0 , however that did not help 

![image](https://github.com/user-attachments/assets/87ffa2a1-fa6e-4564-b686-55c99df19d8c)

2 -  "We were not able to load some functions in the list due to errors. Refresh the page to try again. See details" 
![image](https://github.com/user-attachments/assets/94358027-4b9c-4aab-80e7-1deff416be32)

# Expected behavior

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by yaowilli** [comment]
Issue seem to have gone away by enabling the right same VNet on function App as the storage app
![image](https://github.com/user-attachments/assets/c141ba87-cd82-4f57-8c43-f4ac0ecc43f6)

![image](https://github.com/user-attachments/assets/85f153e5-ca47-4661-96cb-90d8526f27ba)

**Comment by Roopan-Microsoft** [comment]
Great to hear that the issue has been resolved! @yaowilli - Please feel free to open the ticket if any issue in future.
