### ISSUE TITLE
Uploaded documents from admin app is not being indexed into AI search

### ISSUE THREAD

**Issue by yaowilli** [Azure-Samples/chat-with-your-data-solution-accelerator#1236]
# Describe the bug
This issue is seen when documents are ingested in the Admin app, while i expect to see the documents having after ingestion in my index of the AI search service however the documents are not indexed properly 

I also observe that when i ingest document there is no activities in the backend logs at all such as [add_url_embeddings], [batch_push_results] ...etc 

# Expected behavior
expected behavior is to be the ingested documents being properly indexed in the AI search 

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. by simple ingestion of a document into the Admin App 

## Screenshots
![image](https://github.com/user-attachments/assets/8c926b04-69ea-464a-bf85-ccedaedfd081)

![image](https://github.com/user-attachments/assets/0bda8273-d07c-4a8d-8921-b6d77451fc74)

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Prasanjeet-Microsoft** [comment]
@yaowilli Could you please let us know if you are still experiencing this issue? We are asking this because we were unable to replicate this issue using the steps provided, and the ingested documents were being indexed correctly in AI search. Please find below screenshots for your reference:

<img width="950" alt="image" src="https://github.com/user-attachments/assets/cc70c9fa-d348-4b20-a3a6-47e4de5fee25">

<img width="919" alt="Screenshot 2024-09-03 201730" src="https://github.com/user-attachments/assets/e2e7aa95-afa2-4a50-9ad4-8cbb642c1d8b">

<img width="915" alt="Screenshot 2024-09-03 201949" src="https://github.com/user-attachments/assets/c1ccc656-b840-4f5f-97da-225b448aa1f7">

<img width="950" alt="image" src="https://github.com/user-attachments/assets/92668b35-cbd1-40c8-88a1-02a3482b9e78">

**Comment by yaowilli** [comment]
![image](https://github.com/user-attachments/assets/b2fb3ac7-9cb0-4f5e-bdce-34f9d44d05f0)

**Comment by Prasanjeet-Microsoft** [comment]
Hello @yaowilli , Could you please provide us with either your resource group name or the URL of your app service?

**Comment by yaowilli** [comment]
RG1: rg-Crypto-001 - App service: web-5da4cne5rbana.azurewebsites.net

RG2: rg-ipasWiki-001 - App service: web-ej44tydj6vdok.azurewebsites.net

**Comment by Prasanjeet-Microsoft** [comment]
Hello @yaowilli Could you please specify the tenant and subscription name under which this resource group has been deployed in Azure?

**Comment by yaowilli** [comment]
Subscription name: WilliamYao

**Comment by yaowilli** [comment]
Tenant ID: 46c98d88-e344-4ed4-8496-4ed7712e255d

**Comment by Roopan-Microsoft** [comment]
Hi @yaowilli,

As we continue to investigate the issue, could you please verify whether the keys listed below are included in your configuration? Additionally, kindly double-check that the API key values are correct.

Link: [Configuration Details](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/LOCAL_DEPLOYMENT.md#environment-variables)

**Comment by yaowilli** [comment]
![image](https://github.com/user-attachments/assets/4d8e89c4-0360-416c-a000-499a795544ba)

![image](https://github.com/user-attachments/assets/d0d25f25-2e94-4b94-ae25-00376d7135eb)

**Comment by yaowilli** [comment]
do you see anything wrong in my configuration?

**Comment by Prasanjeet-Microsoft** [comment]
Hello @yaowilli , Could you please change the value of **USE_KEY_VAULT** from false to true and then check if you can load all the pages of the admin app properly.

**Comment by yaowilli** [comment]
Hi setting the USE_KEY_VAULT to True, seems to be making difference, let me run some more testing next week and let you know thanks

**Comment by yaowilli** [comment]
would you mind sharing what was the issue ?

**Comment by Prasanjeet-Microsoft** [comment]
> would you mind sharing what was the issue ?

After investigating on the issues that you mentioned above, we found that there is a problem accessing the value of keys (OPENAI_API_KEY and AZURE_BLOB_ACCOUNT_KEY). The value of these keys are retrieved from the Key Vault secret and for this process to work correctly, the USE_KEY_VAULT setting must be enabled (i.e. set to true).

Note:- If USE_KEY_VAULT is set to "true", it initializes a SecretClient object using the AZURE_KEY_VAULT_ENDPOINT environment variable and the DefaultAzureCredential.

**Comment by Prasanjeet-Microsoft** [comment]
@yaowilli Could you please provide an update on the actual issue regarding **documents uploaded from the admin app not being indexed by the AI search**? Additionally, could you please create a new GitHub issue for the chat app problem?

**Comment by yaowilli** [comment]
@Prasanjeet-Microsoft thank you the errors seen from the admin App are gone now thank you - I am in the process of ingesting more documents and check against the indexes count.

**Comment by Prasanjeet-Microsoft** [comment]
@yaowilli Thank you for the update. If the ingested documents are indexed correctly in the AI search, could you please go ahead and close this issue?

**Comment by yaowilli** [comment]
it is closed

**Comment by Roopan-Microsoft** [comment]
Hey thanks @yaowilli. I'm glad to hear your issue has been resolved! If you encounter any other problems, please feel free to open a new issue.

Happy to help!
