### ISSUE TITLE
With Poetry not installed, `azd up` fails

### ISSUE THREAD

**Issue by bwateratmsft** [Azure-Samples/chat-with-your-data-solution-accelerator#1251]
# Describe the bug
With Poetry not installed, `azd up` fails

# Expected behavior
AZD should install Poetry as part of the prepackaging steps

# How does this bug make you feel?
☹ 

---

# Debugging information

## Steps to reproduce
1. `azd init -t https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator`
2. `azd up`

## Logs
```
PS D:\Sandbox\ChatWithData> azd up

Packaging services (azd package)

  (x) Failed: Packaging service adminweb

ERROR: error executing step command 'package --all': failed packaging service 'adminweb': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '1', Path: 'C:\Users\MyUser\AppData\Local\Temp\azd-prepackage-4074018583.ps1'. : exit code: 1, stdout: , stderr: poetry: C:\Users\MyUser\AppData\Local\Temp\azd-prepackage-4074018583.ps1:4
Line |
   4 |  poetry install; poetry export -o requirements.txt
     |  ~~~~~~
     | The term 'poetry' is not recognized as a name of a cmdlet, function, script file, or executable program. Check
     | the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Comment by Roopan-Microsoft** [comment]
Hey @bwateratmsft - Just want to know if you followed the same https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/NON_DEVCONTAINER_SETUP.md.

If not, please try following these steps as we have a shell script where it will install all required packages.

Please let me know in case any further issue.

**Comment by bwateratmsft** [comment]
I did not follow these steps, didn't see them before I tried `azd up`. If it's expected that Poetry is not auto-installed during `azd up` then this issue can be resolved.

**Comment by Roopan-Microsoft** [comment]
Yes, we need to execute the shell script as outlined.

Thank you for your understanding. I’m closing this issue for now, but please don’t hesitate to open a new issue if you have any further questions or concerns.
