### ISSUE TITLE
Use of vector search

### ISSUE THREAD

**Issue by czajek** [Azure-Samples/chat-with-your-data-solution-accelerator#127]
If my understanding of the flow is correct as a part of document indexing / ingestion proccess, each document is chunked and for each chunk embeddings are created and stored in AI Search as vectors.
According to the code referenced below, vector search is not used as the only search options available are "simple" and "semantic". Other search type queries like vector, vectorSimpleHybrid, vectorSemanticHybrid seems not to be supported. Does it mean that this accelerator in current shape doesn't use embeddings during search?

https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/1a95926e96b4ad94f79363ef68fbb1643c93db8f/code/app/app.py#L102C21-L102C21

**Comment by ruoccofabrizio** [comment]
@czajek By default the frontend call the /api/conversation/custom API [https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/1a95926e96b4ad94f79363ef68fbb1643c93db8f/code/app/app.py#L270](app.py)
The Orchestrator class handles the request calling a QuestionAnswerTool, which uses hybrid search [https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/1a95926e96b4ad94f79363ef68fbb1643c93db8f/code/utilities/tools/QuestionAnswerTool.py#L27C47-L27C47](QuestionAnswerTool.py)

**Comment by ross-p-smith** [comment]
@czajek are you satisfied with this answer?
