### ISSUE TITLE
Internal Server Error and other issues

### ISSUE THREAD

**Issue by privileger** [Azure-Samples/chat-with-your-data-solution-accelerator#1307]
### Discussed in https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/discussions/1303

<div type='discussions-op-text'>

<sup>Originally posted by **privileger** September 10, 2024</sup>
Hi everyone,

I deployed this repo a couple of months ago and used it without any issues. Today, I deployed it again in a demo environment, but the front-end application is not running properly, showing an 'Internal Server Error.' The backend application is running; however, after uploading the document for indexing, it is throwing multiple errors.

The template was deployed without modifications. I only added the Japanese language "ja-JP" in the list of supported languages during the deployment. 

Please advise how to resolve this issue.

![000](https://github.com/user-attachments/assets/d41cb619-5fc1-4883-9640-59697f919fad)
<img width="335" alt="001" src="https://github.com/user-attachments/assets/371b4d0d-4b5d-419e-8a96-11ece4385f3e">
<img width="950" alt="002" src="https://github.com/user-attachments/assets/11a8951b-1e8f-46a7-91de-8fe5e6666245">

</div>

**Comment by Roopan-Microsoft** [comment]
Hey @privileger - Thanks for your feedback. We already fixed this issue and merged as part of #1305.

Please try to redeploy and see if you are still facing the issue, please let us know.

Happy to Help!

**Comment by Prasanjeet-Microsoft** [comment]
Hello @privileger, We are closing this issue now since it has already been fixed as part of PR https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1305. We have also addressed other related issues in the discussion panel. If you still encounter the issue, please feel free to reopen it. We're here to help if you need any assistance! 😃
