### ISSUE TITLE
Admin App can not be used behind a proxy which block websocket

### ISSUE THREAD

**Issue by deuch** [Azure-Samples/chat-with-your-data-solution-accelerator#131]
# Motivation

Admin Webapp is build with streamlit and it can not work if a corporate proxy refused the weksocket connection for security purpose.

Is it possible to have the admin webapp in node.js instead of streamlit please ? Like the Chat app :)

Thanks

# Requirements

- Allow the Admin app to be accessed without a websocket.

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by deuch** [comment]
Hello,

Any update on this issue ? My FSI consumer is blocking the deployment because of the websocket needed by streamlit.

Thanks

**Comment by Lawndemon** [comment]
I believe the only workaround for this is to have the URL whitelisted or to completely swap out the front-end architecture and shift away from streamlit
