### ISSUE TITLE
Notifications for end of document processing

### ISSUE THREAD

**Issue by deuch** [Azure-Samples/chat-with-your-data-solution-accelerator#132]
# Motivation

It's currently unclear when the backend processing of documents is complete. It would be nice to have a notification or progress bar to show the progress.

# Requirements

- Allow the progress of backend processing to be viewed

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
What type of notification were you thinking @deuch ? Is this just a notification in the Admin website?

**Comment by deuch** [comment]
Hello, a banner on the top of the page for example, a kind of visual notification to let you know that the process is finish or in error.
