### ISSUE TITLE
bug: Breaking Change to Environment Variables for Model Info

### ISSUE THREAD

**Issue by cmw2** [Azure-Samples/chat-with-your-data-solution-accelerator#1352]
# Describe the bug
The most recent release from PR #1347 has a breaking change around how model information is read from environment variables.  Specifically, it is looking for new environment variables.  There are scenarios where someone can just reboot their existing deployed app services and this new version will run, but could fail since the new environment variables aren't in place.  

The default deployment using Azure One Deploy button runs the App Services as containers pulling from latest version of docker images.  When they reboot they will pull latest image.  However, if they have customized the values for their models, those are no longer used with the latest code change.  This can lead to using the incorrect model or errors if they haven't deployed those default models.

# Expected behavior
The solution should continue to work as configured even after receiving latest version. 
 Ideally the previous environment variables should be used if the new ones aren't available so existing deployed solutions still work.

# Workaround 
Users encountering this should add new environment variables in the new format, something like:

- AZURE_OPENAI_MODEL_INFO={"model":"gpt-4o","modelName":"gpt-4o","modelVersion":"2024-05-13"}

- AZURE_OPENAI_EMBEDDING_MODEL_INFO={"model":"text-embedding-ada-002","modelName":"text-embedding-ada-002","modelVersion":"2"}
  (May need to escape quotes but I didn't need to in App Service settings.)

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. Reboot an already existing deployed accelerator web front end that is docker based using the public images, but is configured to use non-standard model deployments (like gpt-4o) and the default model isn't deployed to the AOAI instance.
2. Note that a new docker image is pulled.
3. Try to use the chat.  There will be an error message in the UI.  When researching logs will see calls to the default model, not the expected model (like gpt-4o).

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by strudel0209** [comment]
subscribing to the above. thanks for the workaround @cmw2

**Comment by Roopan-Microsoft** [comment]
Hi @cmw2 - Thank you for your feedback and for sharing the workaround. We're addressing this as a top priority.

**Comment by Roopan-Microsoft** [comment]
Hey @cmw2, @strudel0209  - We have fixed this issue as part of #1356. So below is the fix

- Reading the old env variables if user doesn't have the new model info.

Let me know if you still face any issues. Happy to Help!

**Comment by strudel0209** [comment]
@Roopan-Microsoft , thank you! seems to work as expected :)
