### ISSUE TITLE
Can not use byod

### ISSUE THREAD

**Issue by TheModin** [Azure-Samples/chat-with-your-data-solution-accelerator#1370]
# Describe the bug
After successfully deploying the solution with the variables according to: [instructions](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/contract_assistance.md)

# Expected behavior
When setting Conversational flow to "byod" I get the following error when asking something regarding the contracts uploaded.
`Cannot read properties of undefined (reading '0')`

---

# Debugging information

## Steps to reproduce
1. Deploy the solution according to [info](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/contract_assistance.md)
2. Upload contracts from sample folder
3. Change conversational flow to "byod" in the admin interface
4. Ask a question "list all contracts ....."
5. See error `Cannot read properties of undefined (reading '0')`

## Screenshots
![image](https://github.com/user-attachments/assets/d4cb14c2-4ba3-4c1c-9b62-a7f74769c3e4)

## Logs

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Roopan-Microsoft** [comment]
Hi @TheModin - Thanks for your feedback.

We will investigate from our end; meanwhile can you please share us the exceptions from App Insights if any.

Thanks for your patience!

**Comment by TheModin** [comment]
Hi.
Not sure what to look in to here.
![image](https://github.com/user-attachments/assets/6e950333-40eb-43a2-8cbd-71d8b991db2b)

**Comment by Roopan-Microsoft** [comment]
Hey @TheModin ,Thank you for the update. We attempted to reproduce the issue on our end but were unable to do so following your steps. Please try redeploying the latest code and let us know if the problem persists.

In the meantime, could you please provide more details? Below, we’ve highlighted the steps for fetching the information.
<img width="596" alt="image" src="https://github.com/user-attachments/assets/afc2d0bf-007e-487c-ac6e-357cb351a0ba">

Similar way please collect for other failures as well.

**Comment by TheModin** [comment]
I have redeployed.
Some more information. I am using rbac, since there are some policies in place that disables the option to use keys.
There was a lot of errors saying that the PrinipalID of the web front did not have permissions, so I added permissions at the resource group level according to [Manually assign roles](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/LOCAL_DEPLOYMENT.md#manually-assign-roles), but that didn't help. I then followed [this](https://learn.microsoft.com/en-gb/azure/cosmos-db/nosql/security/how-to-grant-data-plane-role-based-access?tabs=built-in-definition%2Cpython&pivots=azure-interface-cli#permission-model). That made the rbac error go away, but it still doesn't work, same error.
Attaching log from App insights.
[batch_push_results.txt](https://github.com/user-attachments/files/17249226/batch_push_results.txt)
[InProc.txt](https://github.com/user-attachments/files/17249294/InProc.txt)
![image](https://github.com/user-attachments/assets/cc25ebaa-cafa-43e7-bfc2-1492b22484f6)

**Comment by TheModin** [comment]
It also looks like the function app is still trying to use keys even though it's deployed with rbac variables.
`Key based authentication is not permitted on this storage account.
RequestId:c701061c-6003-0028-4524-16ea53000000
Time:2024-10-04T06:13:14.3591380Z
Status: 403 (Key based authentication is not permitted on this storage account.)
ErrorCode: KeyBasedAuthenticationNotPermitted

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>KeyBasedAuthenticationNotPermitted</Code><Message>Key based authentication is not permitted on this storage account.
RequestId:c701061c-6003-0028-4524-16ea53000000
Time:2024-10-04T06:13:14.3591380Z</Message></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: c701061c-6003-0028-4524-16ea53000000
x-ms-error-code: KeyBasedAuthenticationNotPermitted
Date: Fri, 04 Oct 2024 06:13:13 GMT
Content-Length: 269
Content-Type: application/xml
 `
![image](https://github.com/user-attachments/assets/93e7c53e-1d17-4030-9d93-7ffe80edc344)

**Comment by Roopan-Microsoft** [comment]
Hey @TheModin,

please check the "Allow storage account key access" option in your storage account settings. Ensure that it is enabled. If it is disabled, enable it and test again.

<img width="535" alt="image" src="https://github.com/user-attachments/assets/2d81102b-2097-41f6-8998-efc42fd9b193">

Please let me know if its resolved.

**Comment by Roopan-Microsoft** [comment]
Hi @TheModin - Hope your issue is resolved.

I'm closing this issue for now. Please feel free to reopen it if any problems arise. I'm happy to help!
