### ISSUE TITLE
The account type 'ContentSafety' is either invalid or unavailable in given region.

### ISSUE THREAD

**Issue by gehudd-MSFT** [Azure-Samples/chat-with-your-data-solution-accelerator#1378]
# Describe the bug
When deploying from custom template, received error "The account type 'ContentSafety' is either invalid or unavailable in given region." on template validation via ['Deploy to Azure'](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure-Samples%2Fchat-with-your-data-solution-accelerator%2Fmain%2Finfra%2Fmain.json) despite testing deploying the Azure AI Content Safety service successfully in isolation, to multiple regions. Also confirmed issue reproduced by different user.

# Expected behavior
Deployment to validate and deploy successfully

# How does this bug make you feel?
![Alt Text](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDRwOWgxc2xqbHlpdXY5aTh6Z3BmNzJ5bmxyeHhsaDNzdzN0cWtmeCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BEob5qwFkSJ7G/giphy.gif)

---

# Debugging information

## Steps to reproduce
1. Go to [here](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator?tab=readme-ov-file#deploy-instructions)
2. Click on ['Deploy to Azure'](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure-Samples%2Fchat-with-your-data-solution-accelerator%2Fmain%2Finfra%2Fmain.json)
3. Create new RG
4. Set region as East US / Canada Central / UK South
5. Click 'Review + Create'

## Screenshots
![image](https://github.com/user-attachments/assets/fb09eb78-65c7-4f9f-80af-347b97180ac2)
![image](https://github.com/user-attachments/assets/c74f0ac8-d49b-4131-943a-620ec2c94b18)

**Comment by Roopan-Microsoft** [comment]
Hey @gehudd-MSFT, Thanks for your feedback. 

We will investigate the issue and keep you posted.

Meanwhile can you confirm if any parameter you customized during the deployment?

**Comment by Prasanjeet-Microsoft** [comment]
Hello @gehudd-MSFT , It seems you are attempting to deploy this accelerator in the Canada Central region, **which does not support the Azure Content Safety service**. Please consider deploying it in another region where this service is available. You can find the relevant information in the link below:
https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/#products-by-region_tab1

Additionally, check the parameter values for the **Azure Open AI Model, Azure Open AI Model Name and Azure Open AI Model Version**, and select the appropriate regions accordingly before initiating the deployment. Please find the below image for your reference.

<img width="760" alt="image" src="https://github.com/user-attachments/assets/b6edf759-4470-48d7-9099-4d50c38f154f">

Also if you prefer not to use the same Azure OpenAI model, you can change it based on your requirements. However, please review the link below before initiating the deployment.

https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models?tabs=python-secure#model-summary-table-and-region-availability

Thank you.

**Comment by gehudd-MSFT** [comment]
@Prasanjeet-Microsoft as mentioned in the repro steps, repeated this in East US and UK South tot he same result. Also mentioned: was able to create the service in those regions manually.

**Comment by gehudd-MSFT** [comment]
Issue resolved - intermittent issue on service availability
