### ISSUE TITLE
One Click Deployment fails due to invalid AOAI quote, then continues to fail when corrected

### ISSUE THREAD

**Issue by luca-stamatescu** [Azure-Samples/chat-with-your-data-solution-accelerator#138]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

This issue is fairly minor- just FYI as may confuse other users.

Issue:
Click the "one click deployment"
Enter a region that either has insufficient AOAI quota or AOAI is unavailable in that region
Click review and create
Validation fails
Go back and change the region to a valid region
The validation will (incorrectly) continue to fail

Workaround:
Delete the resource group created during the steps above
Close browser
Click "One Click Deployment"
Choose a valid region

### Any log messages given by the failure
>
NA

### Expected/desired behavior
>
Should be able to revert to the first page and choose a valid region.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
NA

### Versions
>
Current
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
I think this may be out of scope for this repo to solve as this is a problem with the scope of the bicep deployment. It uses the rg location to deploy the child resources. Maybe when azd is added we can relook at this. Until then, might be worth adding some docs around this
