### ISSUE TITLE
Codespaces Deployment Failed

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/chat-with-your-data-solution-accelerator#139]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> azd up

### Any log messages given by the failure
>
  Packaging service teams (Building Docker image from source)
  (x) Failed: Packaging service teams

ERROR: failed building service 'teams': failing invoking action 'build', exit code: 1, stdout: debian-bullseye-20231107.2: Pulling from oryx/builder
Digest: sha256:cbbc0cb40fccb6c34e334bab5fcc0cbef388b8501b403b5341fd8e79417b1de6
Status: Image is up to date for mcr.microsoft.com/oryx/builder:debian-bullseye-20231107.2
stack-run-debian-bullseye-20230926.1: Pulling from oryx/builder
Digest: sha256:b4e65a33543997bab33856cb8cad948aa5b12dd152c34b1f1d6db9ec190e73dc
Status: Image is up to date for mcr.microsoft.com/oryx/builder:stack-run-debian-bullseye-20230926.1
0.17.0: Pulling from buildpacksio/lifecycle
Digest: sha256:bc0d791f89bda0e8fbf9bf3e47c2faf1ac4eca4b16f0b01c6cb606883759766a
Status: Image is up to date for buildpacksio/lifecycle:0.17.0
===> ANALYZING
[analyzer] Timer: Analyzer started at 2024-01-08T13:41:00Z
[analyzer] Image with name "chat-with-your-data-solution-accelerator-teams" not found
[analyzer] Timer: Analyzer ran for 39.042µs and ended at 2024-01-08T13:41:00Z
===> DETECTING
[detector] Warning: Platform requested experimental feature 'Dockerfiles'
[detector] Timer: Detector started at 2024-01-08T13:41:02Z
[detector] oryx/node-runtime 0.0.1
[detector] oryx/node-install 0.0.1
[detector] fagiani/apt       0.2.5
[detector] oryx/node-build   0.0.1
[detector] Timer: Detector ran for 7.594435383s and ended at 2024-01-08T13:41:09Z
[detector] Timer: Generator started at 2024-01-08T13:41:09Z
[detector] Loading environment variables from existing 'oryx.env' file.
[detector] Timer: Generator ran for 14.975379ms and ended at 2024-01-08T13:41:09Z
[detector] ERROR: failed to build: exit status 1
, stderr: [detector] /cnb/extensions/oryx_node-runtime/0.0.1/bin/common: line 19: export: `||': not a valid identifier
[detector] /cnb/extensions/oryx_node-runtime/0.0.1/bin/common: line 19: export: `18': not a valid identifier
ERROR: failed to build: executing lifecycle: failed with status code: 91

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Linux
### Versions
>

### Mention any other details that might be useful
azd up deployment failed. Please try to help. Thanks!
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
Hey there. `azd` support has not been implemented yet, but I know it is being worked on under #96. I cant give you an exact time frame, but soon!

If you want to deploy locally, you should be able to use the vscode extension to right click on the bicep file and "Deploy Bicep file . . .". 

Thank you for this. I've linked this to #96

**Comment by mirojs** [comment]
@ross-p-smith Thanks for the quick response! What I'm looking for is deploying to Azure cloud based on the local code changes in Codespaces (changes to the cloned files from the Github) and I'd tried the two deployment methods mentioned in the reame file. None of them could take care of the code changes if I'm not wrong.

Could you let me know a way to make that happen before the azd could work eventually. Thanks!

**Comment by ross-p-smith** [comment]
@mirojs - I haven't looked, but I assume that the deployment uses "known" containers. So you would have to make your code changes, deploy them to an Azure Container Registry and then change the code to use your containers rather than the maintainers of this repo. Does that make sense?

**Comment by mirojs** [comment]
@ross-p-smith Thanks. Got the azd worked out and can give this a try. Hopefully a fix could be released soon.

**Comment by mirojs** [comment]
Pressed the wrong button just now by chance

**Comment by ross-p-smith** [comment]
I think we need to 
- [ ] Add an ACR to the deployment
- [ ] Have local tooling to be able to build and push images to the ACR
- [ ] Allow local deployment to use your own acr rather than the public one should you enter it into your .env file
