### ISSUE TITLE
Front-end UI displays Authentication Error when enabled vnet integration and private endpoint

### ISSUE THREAD

**Issue by jmasengeshomsft** [Azure-Samples/chat-with-your-data-solution-accelerator#1390]
# Describe the bug
On the frontend chat app, I did the following:

1. Add private endpoint
2. Enabled vnet integration
3. Disabled public access

After that, the screenshot below started to appear.

# Expected behavior
The app should display the chat UI

---

# Debugging information

## Steps to reproduce
Enabled vnet security on the chat UI

## Screenshots
![image](https://github.com/user-attachments/assets/e9b1dee5-7aa3-45bf-8a37-c275fd4d5e9a)

Where is this error/warning coming from: 

_This app does not have authentication configured. Please add an identity provider by finding your app in the [Azure Portal](https://portal.azure.com/) and following [these instructions](https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service#3-configure-authentication-and-authorization)._

**Comment by jmasengeshomsft** [comment]
I discovered the issue. The container registry reference in main.bicep will always pull the latest image, even if the local infrastructure is outdated. I was running a forked version of the app, but the container expected authentication to be enabled. No further action is needed, though it might be a good idea to create a PR to parameterize the container registry, image, and tag.

**Comment by Roopan-Microsoft** [comment]
Thanks @jmasengeshomsft for your feedback.
