### ISSUE TITLE
Unexpected Increase in Costs + Q&A not working

### ISSUE THREAD

**Issue by devanshithakar12** [Azure-Samples/chat-with-your-data-solution-accelerator#1392]
I have been using this Github repo along with others, and have noticed a significant increase in costs overnight. I am seeing assistance or guidance on identifying the factors contributing to this sudden spike in expenses. 

I only have a few pdf documents that I am working with. I am able to upload the documents, but not able to chat with the documents. 

Would love any best practices or possible solutions. Thank you!

---

# Tasks
- [ ] Costs
- [ ] Q&A

**Comment by Roopan-Microsoft** [comment]
Hi @devanshithakar12, thanks for your feedback!

Could you please specify the exact issue you’re encountering? Additionally, if you could provide the following details, it would be helpful:
- Any exceptions from App Insights
- A UI screenshot indicating where you're unable to chat with documents

You might also want to check if your documents have been processed by looking at 'Explore Data' on the Admin page to see if your uploaded documents appear there.

Looking forward to your response. Thanks!

**Comment by devanshithakar12** [comment]
@Roopan-Microsoft ,

Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks!
<img width="467" alt="Screenshot 2024-10-09 175655" src="https://github.com/user-attachments/assets/db98639c-b25b-47d6-b3e9-2a645e709901">

**Comment by devanshithakar12** [comment]
@Roopan-Microsoft , 

In addition, is there a way to get a cost estimate of deploying this accelerator to Azure? Happy to sync offline on this as well! Thanks.

**Comment by Roopan-Microsoft** [comment]
> @Roopan-Microsoft ,
> 
> In addition, is there a way to get a cost estimate of deploying this accelerator to Azure? Happy to sync offline on this as well! Thanks.

We will provide you that.

**Comment by Roopan-Microsoft** [comment]
> @Roopan-Microsoft ,
> 
> Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks! <img alt="Screenshot 2024-10-09 175655" width="467" src="https://private-user-images.githubusercontent.com/33441411/375174853-db98639c-b25b-47d6-b3e9-2a645e709901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjc5MTAsIm5iZiI6MTcyODYyNzYxMCwicGF0aCI6Ii8zMzQ0MTQxMS8zNzUxNzQ4NTMtZGI5ODYzOWMtYjI1Yi00N2Q2LWIzZTktMmE2NDVlNzA5OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjc4YTE5NWFjNDU3YWI4OWU0ZmNjNmVhZDBjODdlYjY3ZmIzZDk2YzM3YzcyMGFiYTY5NmIyMDg1ODhjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WibGPzncwpf8Uj1pVGrsxq0S-GqmBhRKC6Y_aaj93Rc">

This seems like some configuration issue, please let us know if we can connect offline and fix it.

**Comment by devanshithakar12** [comment]
> > @Roopan-Microsoft ,
> > Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks! <img alt="Screenshot 2024-10-09 175655" width="467" src="https://private-user-images.githubusercontent.com/33441411/375174853-db98639c-b25b-47d6-b3e9-2a645e709901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjc5MTAsIm5iZiI6MTcyODYyNzYxMCwicGF0aCI6Ii8zMzQ0MTQxMS8zNzUxNzQ4NTMtZGI5ODYzOWMtYjI1Yi00N2Q2LWIzZTktMmE2NDVlNzA5OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjc4YTE5NWFjNDU3YWI4OWU0ZmNjNmVhZDBjODdlYjY3ZmIzZDk2YzM3YzcyMGFiYTY5NmIyMDg1ODhjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WibGPzncwpf8Uj1pVGrsxq0S-GqmBhRKC6Y_aaj93Rc">
> 
> This seems like some configuration issue, please let us know if we can connect offline and fix it.

Happy to connect offline - what is your alias/the best way to reach out?

**Comment by Roopan-Microsoft** [comment]
> > > @Roopan-Microsoft ,
> > > Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks! <img alt="Screenshot 2024-10-09 175655" width="467" src="https://private-user-images.githubusercontent.com/33441411/375174853-db98639c-b25b-47d6-b3e9-2a645e709901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjc5MTAsIm5iZiI6MTcyODYyNzYxMCwicGF0aCI6Ii8zMzQ0MTQxMS8zNzUxNzQ4NTMtZGI5ODYzOWMtYjI1Yi00N2Q2LWIzZTktMmE2NDVlNzA5OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjc4YTE5NWFjNDU3YWI4OWU0ZmNjNmVhZDBjODdlYjY3ZmIzZDk2YzM3YzcyMGFiYTY5NmIyMDg1ODhjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WibGPzncwpf8Uj1pVGrsxq0S-GqmBhRKC6Y_aaj93Rc">
> > 
> > 
> > This seems like some configuration issue, please let us know if we can connect offline and fix it.
> 
> Happy to connect offline - what is your alias/the best way to reach out?

Thanks for the update, just want to know how you Enabled the Authentication.

**Comment by devanshithakar12** [comment]
> > > > @Roopan-Microsoft ,
> > > > Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks! <img alt="Screenshot 2024-10-09 175655" width="467" src="https://private-user-images.githubusercontent.com/33441411/375174853-db98639c-b25b-47d6-b3e9-2a645e709901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjc5MTAsIm5iZiI6MTcyODYyNzYxMCwicGF0aCI6Ii8zMzQ0MTQxMS8zNzUxNzQ4NTMtZGI5ODYzOWMtYjI1Yi00N2Q2LWIzZTktMmE2NDVlNzA5OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjc4YTE5NWFjNDU3YWI4OWU0ZmNjNmVhZDBjODdlYjY3ZmIzZDk2YzM3YzcyMGFiYTY5NmIyMDg1ODhjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WibGPzncwpf8Uj1pVGrsxq0S-GqmBhRKC6Y_aaj93Rc">
> > > 
> > > 
> > > This seems like some configuration issue, please let us know if we can connect offline and fix it.
> > 
> > 
> > Happy to connect offline - what is your alias/the best way to reach out?
> 
> Thanks for the update, just want to know how you Enabled the Authentication.

Followed these steps: https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service?tabs=workforce-configuration.

**Comment by Roopan-Microsoft** [comment]
> > > > > @Roopan-Microsoft ,
> > > > > Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks! <img alt="Screenshot 2024-10-09 175655" width="467" src="https://private-user-images.githubusercontent.com/33441411/375174853-db98639c-b25b-47d6-b3e9-2a645e709901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjc5MTAsIm5iZiI6MTcyODYyNzYxMCwicGF0aCI6Ii8zMzQ0MTQxMS8zNzUxNzQ4NTMtZGI5ODYzOWMtYjI1Yi00N2Q2LWIzZTktMmE2NDVlNzA5OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjc4YTE5NWFjNDU3YWI4OWU0ZmNjNmVhZDBjODdlYjY3ZmIzZDk2YzM3YzcyMGFiYTY5NmIyMDg1ODhjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WibGPzncwpf8Uj1pVGrsxq0S-GqmBhRKC6Y_aaj93Rc">
> > > > 
> > > > 
> > > > This seems like some configuration issue, please let us know if we can connect offline and fix it.
> > > 
> > > 
> > > Happy to connect offline - what is your alias/the best way to reach out?
> > 
> > 
> > Thanks for the update, just want to know how you Enabled the Authentication.
> 
> Followed these steps: https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service?tabs=workforce-configuration.

Thanks @devanshithakar12  - Could you please see this reference in case if you have missed any step for adding authentication and then let us know the result.

**Comment by Prasanjeet-Microsoft** [comment]
> > > > > > @Roopan-Microsoft ,
> > > > > > Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks! <img alt="Screenshot 2024-10-09 175655" width="467" src="https://private-user-images.githubusercontent.com/33441411/375174853-db98639c-b25b-47d6-b3e9-2a645e709901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjc5MTAsIm5iZiI6MTcyODYyNzYxMCwicGF0aCI6Ii8zMzQ0MTQxMS8zNzUxNzQ4NTMtZGI5ODYzOWMtYjI1Yi00N2Q2LWIzZTktMmE2NDVlNzA5OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjc4YTE5NWFjNDU3YWI4OWU0ZmNjNmVhZDBjODdlYjY3ZmIzZDk2YzM3YzcyMGFiYTY5NmIyMDg1ODhjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WibGPzncwpf8Uj1pVGrsxq0S-GqmBhRKC6Y_aaj93Rc">
> > > > > 
> > > > > 
> > > > > This seems like some configuration issue, please let us know if we can connect offline and fix it.
> > > > 
> > > > 
> > > > Happy to connect offline - what is your alias/the best way to reach out?
> > > 
> > > 
> > > Thanks for the update, just want to know how you Enabled the Authentication.
> > 
> > 
> > Followed these steps: https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service?tabs=workforce-configuration.
> 
> Thanks @devanshithakar12 - Could you please see this reference (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/web-apps.md#add-authentication-in-azure-app-service-configuration) in case if you have missed any step for adding authentication and then let us know the result.

@devanshithakar12 Did you had a chance to look into this? Could you please provide me any further updates?

**Comment by Prasanjeet-Microsoft** [comment]
> > > > > > > @Roopan-Microsoft ,
> > > > > > > Thank you for your quick response! I figured out the initial error from Azure Function logs and updated the TPM for my embedding model. With this change, I was able to successfully see the docs in Azure Storage and indexed into AI Search. When I opened the web app, however, I am getting an Authentication error. I have created an app registration and attached it to my Identity provider, but no luck. Attached the error below. Thanks! <img alt="Screenshot 2024-10-09 175655" width="467" src="https://private-user-images.githubusercontent.com/33441411/375174853-db98639c-b25b-47d6-b3e9-2a645e709901.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mjc5MTAsIm5iZiI6MTcyODYyNzYxMCwicGF0aCI6Ii8zMzQ0MTQxMS8zNzUxNzQ4NTMtZGI5ODYzOWMtYjI1Yi00N2Q2LWIzZTktMmE2NDVlNzA5OTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA2MjAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjc4YTE5NWFjNDU3YWI4OWU0ZmNjNmVhZDBjODdlYjY3ZmIzZDk2YzM3YzcyMGFiYTY5NmIyMDg1ODhjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WibGPzncwpf8Uj1pVGrsxq0S-GqmBhRKC6Y_aaj93Rc">
> > > > > > 
> > > > > > 
> > > > > > This seems like some configuration issue, please let us know if we can connect offline and fix it.
> > > > > 
> > > > > 
> > > > > Happy to connect offline - what is your alias/the best way to reach out?
> > > > 
> > > > 
> > > > Thanks for the update, just want to know how you Enabled the Authentication.
> > > 
> > > 
> > > Followed these steps: https://learn.microsoft.com/en-us/azure/app-service/scenario-secure-app-authentication-app-service?tabs=workforce-configuration.
> > 
> > 
> > Thanks @devanshithakar12 - Could you please see this reference (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/web-apps.md#add-authentication-in-azure-app-service-configuration) in case if you have missed any step for adding authentication and then let us know the result.
> 
> @devanshithakar12 Did you had a chance to look into this? Could you please provide me any further updates?

Hello @devanshithakar12, Just checking in to see if you’ve had a chance to review this? I'd appreciate any updates you might have.

Thank you.

**Comment by devanshithakar12** [comment]
Hi @Prasanjeet-Microsoft, unfortunately tried those steps and still facing the same issue. Is there a way to connect offline? Thanks!

**Comment by Prasannakatakam-Microsoft** [comment]
Hello @devanshithakar12, checking how to connect offline. In the meantime, please share the steps following along with few screenshots.

**Comment by Vinay-Microsoft** [comment]
Hi @devanshithakar12  unfortunately as per our organization policy we can not connect offline so please put all your queries here with detailed steps in a document or video clearly explaining the problem and any queries you might have. Thanks for your patience and understanding.

**Comment by Prasanjeet-Microsoft** [comment]
> > Hi @devanshithakar12 unfortunately as per our organization policy we can not connect offline so please put all your queries here with detailed steps in a document or video clearly explaining the problem and any queries you might have. Thanks for your patience and understanding.
> 
> Hello @devanshithakar12, Just following up on our previous message. It would be really helpful if you could provide a document or video outlining the steps. Your assistance is much appreciated!
> 
> Thank you!

Hello @devanshithakar12 , I am just following up on our previous message. It would be really helpful if you could provide a document or video outlining the steps. Your assistance is much appreciated! Thank you.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @devanshithakar12 , I am just following up on our previous message. It would be really helpful if you could provide a document or video outlining the steps. Your assistance is much appreciated! 

Thank you.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @devanshithakar12 , Since we haven't received any updates from you for a while, we are proceeding to close this issue. However, if you experience any further problems, please don't hesitate to reopen it or create a new one. We are here to help!

Thank you.
