### ISSUE TITLE
Remark on Prompt Flow is misleading

### ISSUE THREAD

**Issue by OliverWill** [Azure-Samples/chat-with-your-data-solution-accelerator#142]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
Understanding of how Prompt Flow could/could not be an alternative to the backend in the `app.py`

### Mention any other details that might be useful

In the "When should you use this repo?" section of the README.MD it is written that "If you need to customize your scenario beyond what [Azure OpenAI on your data](https://learn.microsoft.com/azure/ai-services/openai/concepts/use-your-data) offers out-of-the-box, use this repository" and "If you don't require customizations" then "use [Azure Machine Learning prompt flow](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/overview-what-is-prompt-flow)".

But if you want to customize your scenario beyond the "Azure OpenAI on your data" solution then Prompt Flow is an option, right? It would be really helpful if the documentation could explain how PromptFlow is an alternative to the code in the `app.py` in this solution.

**Comment by gaurarpit** [comment]
This is related to #915

**Comment by OliverWill** [comment]
This issue is solved
