### ISSUE TITLE
Improper Error Handling

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#1422]
# Describe the bug
The following code has been added - which exposes the internal error. This should not be surfaced to the UI.

```python
return (jsonify({"error": str(e)}), 500)
```

# Expected behavior
We should adhere to these guidelines https://owasp.org/www-community/Improper_Error_Handling

## Steps to reproduce
There are 7 occurrences of this in chat_history.py

**Comment by Vinay-Microsoft** [comment]
Thanks @ross-p-smith  for this reporting this issue w'll look into it.

**Comment by Vinay-Microsoft** [comment]
We are evaluating a fix for this Issue once fix is identified will post an update here. Thanks for your patience !!!!

**Comment by Somesh-Microsoft** [comment]
Hi @ross-p-smith, just a friendly reminder that we've completed and tested the fix. Could you please review it and confirm?

**Comment by Somesh-Microsoft** [comment]
Hi @ross-p-smith, Bug fix code changes are completed and tested. Hence Closing the Bug.
