### ISSUE TITLE
Docker file doesn't allow for rebuild

### ISSUE THREAD

**Issue by ben-burke-slalom** [Azure-Samples/chat-with-your-data-solution-accelerator#144]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> The docker file is not set up to rebuild the images when `docker-compose up --build` is implemented. 

### Any log messages given by the failure
> The files will deploy, but they will not build based on the changes made.

### Expected/desired behavior
> I would expect docker to build a new version using all the changes made within the code.

### OS and Version?
> macOS 14.2.1 (23C71)

### Mention any other details that might be useful
The docker compose file may be the issue.

**Comment by ross-p-smith** [comment]
We are no longer using docker images inside the App Service
