### ISSUE TITLE
Dockerfiles use old syntax

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#1464]
# Describe the bug
We are getting warnings in our PR scans that our dockerfiles are using old ENV syntax

# Expected behavior
We see no warnings in Pull Requests around docker.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @ross-p-smith, I just wanted to check if we need to address this issue or not?

Thank you.
