### ISSUE TITLE
Chat Web App Authentication

### ISSUE THREAD

**Issue by asevillano** [Azure-Samples/chat-with-your-data-solution-accelerator#1482]
# Describe the bug
I'm trying to follow the steps described in this [steps](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/1d220f7d7d3aeca15b29da19966fdebab1bd824a/docs/web-apps.md) to configure the authentication of the chat web app but now the "Create new app registration" and "Pick an existing app registration in this directory" options are disabled so I have to create the registration separately, but the in the Entra Admin Center the value of "Service Tree ID" is required, but I can't get it.
The Admin web app does not need it and works fine.

# Expected behavior
The deployment should configure it automatically.

# How does this bug make you feel?
I can't use the solution for a demo.

---

# Debugging information

## Screenshots
![image](https://github.com/user-attachments/assets/d18473c7-4c73-46b4-b5e0-bbba4af84320)

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by Prasannakatakam-Microsoft** [comment]
@asevillano Are you trying to deploy this in the Microsoft Tenant? Looks like yes. If yes then can you please try deploying in external subscription as Microsoft tenant has restrictions of providing the requisite access. 

Please let us know if the issue still persists.

**Comment by Pradheep-Microsoft** [comment]
@asevillano we are waiting for your comments 
if that issue still exists, please let us know.

**Comment by Pradheep-Microsoft** [comment]
@asevillano we are waiting for your comments
if that issue still exists, please let us know.

**Comment by asevillano** [comment]
Hi, sorry for the delay.
I can't use different tenant than the Microsoft one, so the problem persists.
In order to be able to deliver the demo to my customer, I will try to run the web app locally but I can't provide online access to the customer to test it by themselves.

**Comment by Roopan-Microsoft** [comment]
@asevillano - Can you please provide the details on which tenant you are trying to deploy?

**Comment by Prasannakatakam-Microsoft** [comment]
@asevillano - Can you please provide the details on which tenant you are trying to deploy?

**Comment by Prasannakatakam-Microsoft** [comment]
@asevillano - Can you please provide the details on which tenant you are trying to deploy?

**Comment by Prasannakatakam-Microsoft** [comment]
@asevillano - Can you please provide the details on which tenant you are trying to deploy?

**Comment by Pradheep-Microsoft** [comment]
@asevillano - can you please provide the details on which tenant you are trying to deploy?

**Comment by asevillano** [comment]
hi, I'm deploying to "MSFT Non-production" tenant, that is the only one where as a MSFT employee I am authorized to deploy demos. The deployment worked but I can't access to the chat UI because the access is restricted.

**Comment by Prasanjeet-Microsoft** [comment]
Hello @asevillano, We would like to inform you of an important update regarding the use of Microsoft tenants. The Microsoft team has advised that all users refrain from using the Microsoft tenant going forward. Instead, please utilize the CDX, FDPO shared tenant, or individual Managed User tenants.

Please note that both production and non-production Microsoft tenant subscriptions will now face significant restrictions due to the implementation of new SFI policies over the past year.

We recommend making the switch to the suggested tenants to ensure compliance and avoid any disruptions.

If you have any questions or need assistance with this transition, feel free to reach out.

Thank you.

**Comment by asevillano** [comment]
Thank you Prasanjeet, one question, the admin web app does not need authentication and this problem does not happen. Could it be configurable in the user interface?

**Comment by cyberflying** [comment]
@asevillano , I was also trouble by this issue before, I have just resolved it. Here are some tips FYI:
0. The main thing is to follow this [doc](https://learn.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad?tabs=workforce-configuration#-option-2-use-an-existing-registration-created-separately)

1. about service tree, you can use `az ad sp create-for-rbac` to create it, or if you input some letter about tree id, then a prompt will appear below with e.g, then, you know what to do :)
2.  After created the app registration, config authentication and secret as below:
![1732716023107](https://github.com/user-attachments/assets/bbc95b61-6aca-4dd8-beec-52552c75e412)
![image](https://github.com/user-attachments/assets/bd9eefcf-52cc-464c-a27a-bf23c061a4e6)
3. Config the web app authentication:
![1732716281722](https://github.com/user-attachments/assets/e1b8b434-400f-47a3-bcbd-db59b1504717)

**Comment by Pradheep-Microsoft** [comment]
@asevillano as discussed above we request you switch to the suggested tenant to ensure compliance and avoid any disruptions.

If you have any questions or need assistance with this transition, feel free to reach out.

**Comment by Pradheep-Microsoft** [comment]
@asevillano please let us know if you are facing any issue.
Or will close this bug

**Comment by Pradheep-Microsoft** [comment]
@asevillano  please let us know if you are facing any issue.
Or will close this bug

**Comment by Pradheep-Microsoft** [comment]
@asevillano please let us know if you are facing any issue.
Or will close this bug

**Comment by Prasanjeet-Microsoft** [comment]
Hello @asevillano, Since we haven't received any updates from you for a while, we are proceeding to close this issue. However, if you experience any further problems, please don't hesitate to reopen it or create a new one. We are here to help! 😃 

Thank you.
