### ISSUE TITLE
Chain of thought not answering (using only tool: TextProcessingTool)

### ISSUE THREAD

**Issue by federicocaccialanzaabb** [Azure-Samples/chat-with-your-data-solution-accelerator#198]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> upload a file in english, ask a question in another language (tested with italian and spanish), the answer of the chatbot will be the translation of your question in english. This is due to the chain of thought stopping after using the TextProcessingTool (correctly) but then not using the QuestionAnswerTool. Keep in mind that because of this the the chatbot doesn't answer using the language of the user too.
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/145559864/c3d8b509-d8f4-40f7-9175-9f46456fcb5e)

### Any log messages given by the failure
>
> Entering new AgentExecutor chain...
Thought: This question is in Italian, so I may need to use the text processing tool to understand it.
Action: Text Processing
Action Input: translate to English: quali sono i prerequisiti del commisioning ?
Observation: {"question": "translate to English: quali sono i prerequisiti del commisioning ?", "answer": "\"What are the prerequisites for commissioning?\"", "source_documents": [], "prompt_tokens": 37, "completion_tokens": 8}

> Finished chain.

(It should not finish! It should use the QuestionAnsweringTool afterwards and formulate the answer in english. Finally translating the answer in the language of the question asked)

### Expected/desired behavior
>
Translate the answer in english, using the QuestionAnsweringTool and retrieve the answer in english. Finally translate the question to give to the user in the same language as the question asked.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
After testing a little bit, I find it difficult to trigger the adoption of more than one tool for a single question. It only uses one toll and finishes the chain. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by federicocaccialanzaabb** [comment]
Just an update on this.... The chain is not able to use more than one tool in sequence... I don't think this is the desired behaviour of the chatbot but for sure it impacts is ability to work with multiple languages:

Example 1: question in != than english language
- the thought process use question answering tool and replies with != than english language

Example 2: question in != than english language
- the thought process use question answering tool and replies with english language (it doesn't use TextProcessingTool Afterwards)
- 
Example 3: question in != than english language
- the thought process use TextProcessingTool and translates the question in english. It then reply with the translation not using the TextProcessingTool


I tried to change suffix in langcahin.py with:  """Use the following format:

        Question: the input question you must answer
        Thought: you should always think about what to do
        Action: the action to take, should be one of ["Question Answering", "Text Processing"]
        Action Input: the input to the action
        Observation: the result of the action
        ... (this Thought/Action/Action Input/Observation can repeat N times)
        Thought: I now know the final answer
        Final Answer: the final answer to the original input question

        Begin!

        Chat history: {chat_history}
        Question: {input}
        {agent_scratchpad}
        """
Instead of just """ Begin!

        Chat history: {chat_history}
        Question: {input}
        {agent_scratchpad}"""

No improvements

I tried to leave the suffix as it is and give to the prompt the format instructions such as the prior change in the suffix
prompt= ZeroShotAgent.create_prompt(
            self.tools,
            prefix=prefix,
            format_instructions=FORMAT_INSTRUCTIONS,
            suffix=suffix,
            input_variables=["input", "chat_history", "agent_scratchpad"],
        )
It doesn't  work... still I receive the same examples...

I think there may be some errors in the structure of the chain and agent or there is an inability to understand that the answer should be given to the user in the same language and should be searched every time
( In addition I receive several warnings that the syntax on which the agent is structured and run is going to be deprecated).

**Comment by Prasanjeet-Microsoft** [comment]
@federicocaccialanzaabb We tried using the gpt-4o model in local and also validated this issue in web app (https://web-7dvimfnwkhn44-docker.azurewebsites.net/) from one of the existing deployed resource group of CWYD with gpt-4o model . After multiple attempts we observe that this issue is not getting reproducible in gpt-4o model. So, we are waiting for some quota for the deployment of CWYD with the latest (gpt-4o/gpt-4) model so that we can validate in our environment also.

**Comment by federicocaccialanzaabb** [comment]
Hello @Prasanjeet-Microsoft,
I already addressed this issue, but in order to do so I created a complete new tool.
These new tool has also a language detection check (Azure AI services | Language service) in order to answer the user question.
I use the lang detection in order to handle multi-language capabilities.
I also switched to a gpt 4 model (4-32k or 4o).
With these changes no issue has come up (apart from expected mistakes: such as when question has more than one language used or one-two words question with words that are common between two or more languages), so if you want you can close this issue.

**Comment by Prasanjeet-Microsoft** [comment]
As per the discussion, I am closing this issue.
