### ISSUE TITLE
Can not ingest URL

### ISSUE THREAD

**Issue by bprerad** [Azure-Samples/chat-with-your-data-solution-accelerator#207]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> can not ingest URLs. Deployed on Azure using One Click Deployment and on admin/ingest get the error. With file ingestion nothing happens, but the file is not processed, apart from the upload. I am using keys authentication. Similar happens with rbac.

### Any log messages given by the failure
> ValueError: Error 500: Error: Traceback (most recent call last): File "/home/site/wwwroot/utilities/helpers/ConfigHelper.py", line 61, in get_active_config_or_default blob_client = AzureBlobStorageClient(container_name=CONFIG_CONTAINER_NAME) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/utilities/helpers/AzureBlobStorageHelper.py", line 9, in __init__ env_helper : EnvHelper = EnvHelper() ^^^^^^^^^^^ File "/home/site/wwwroot/utilities/helpers/EnvHelper.py", line 50, in __init__ self.OPENAI_API_KEY = DefaultAzureCredential(exclude_shared_token_cache_credential=True).get_token("https://cognitiveservices.azure.com/.default").token ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/azure/identity/_credentials/default.py", line 225, in get_token token = super().get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/azure/identity/_credentials/chained.py", line 124, in get_token raise ClientAuthenticationError(message=message) azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials. Attempted credentials: EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue. ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint. AzureCliCredential: Azure CLI not found on path AzurePowerShellCredential: PowerShell is not installed AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'. To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/site/wwwroot/AddURLEmbeddings.py", line 25, in add_url_embeddings config = ConfigHelper.get_active_config_or_default() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/utilities/helpers/ConfigHelper.py", line 66, in get_active_config_or_default config = ConfigHelper.get_default_config() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/utilities/helpers/ConfigHelper.py", line 194, in get_default_config return Config(default_config) ^^^^^^^^^^^^^^^^^^^^^^ File "/home/site/wwwroot/utilities/helpers/ConfigHelper.py", line 23, in __init__ self.env_helper = EnvHelper() ^^^^^^^^^^^ File "/home/site/wwwroot/utilities/helpers/EnvHelper.py", line 50, in __init__ self.OPENAI_API_KEY = DefaultAzureCredential(exclude_shared_token_cache_credential=True).get_token("https://cognitiveservices.azure.com/.default").token ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/azure/identity/_credentials/default.py", line 225, in get_token token = super().get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/azure/identity/_credentials/chained.py", line 124, in get_token raise ClientAuthenticationError(message=message) azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials. Attempted credentials: EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue. ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint. AzureCliCredential: Azure CLI not found on path AzurePowerShellCredential: PowerShell is not installed AzureDeveloperCliCredential: Azure Developer CLI could not be found. Please visit https://aka.ms/azure-dev for installation instructions and then,once installed, authenticate to your Azure account using 'azd auth login'. To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
Traceback:
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 531, in _run_script
    self._session_state.on_script_will_rerun(rerun_data.widget_states)
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/state/safe_session_state.py", line 63, in on_script_will_rerun
    self._state.on_script_will_rerun(latest_widget_states)
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 504, in on_script_will_rerun
    self._call_callbacks()
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 517, in _call_callbacks
    self._new_widget_state.call_callback(wid)
File "/usr/local/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 261, in call_callback
    callback(*args, **kwargs)
File "/usr/local/src/myscripts/admin/pages/01_Ingest_Data.py", line 59, in add_urls
    raise ValueError(f'Error {r.status_code}: {r.text}')

### Expected/desired behavior
> Should be able to ingest files/URLs

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> Current

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by komalg1** [comment]
@bprerad Can you let us know when did you deploy? There was an ongoing issue which got fixed yesterday.
Can you re-deploy and check again please?

**Comment by bprerad** [comment]
Yes, I went through the issues and redeployed just minutes before posting. No difference. I will redeploy again, just to be on the safe side.

**Comment by bprerad** [comment]
It works now. great!
