### ISSUE TITLE
Alert loop with 'copy' event listener in chat window

### ISSUE THREAD

**Issue by jtejeroc** [Azure-Samples/chat-with-your-data-solution-accelerator#215]
**/code/app/frontend/src/components/Answer/Answer.tsx**
When using chat webApp and you try to copy the conversation content, on 'copy' event, alert "*Please consider where you paste this content.*" keeps reappearing on a loop after clicking on "Accept". The "clicking" must go on incrementally with the queries sent by the user.
- One user query: alert is shown once and pops out when you click on Accept once.
- Two user queries: alert is shown, click on Accept, pops out and a new one reappears, click Accept again and pops out.
- And so on.

Additional observations:
- It does not matter how many messages are you copying.
- Loop does **NOT** restart if you clear the conversation with the broom icon.
- Loop **restarts only** if you refresh the chat webpage.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Send one or several messages and try to copy content.

### Any log messages given by the failure
> No.

### Expected/desired behavior
> Copy event alert to be shown only once when you copy or even just once per "chat session"; could be set to reappear if "clear chat" is clicked or webpage is refreshed.

### OS and Version?
> Windows 10 Pro (22H2).

### Versions
>

### Mention any other details that might be useful
- Copy event seems to be accumulating as the total user queries increase.
- It does not depend on how many messages do you want to copy.
- Loop does not restart even if you clear the conversation.
- Loop restarts only if you refresh the chat webpage.
> ---------------------------------------------------------------

**Comment by adamdougal** [comment]
@jtejeroc Heya! This issue has now been resolved. Can you deploy the latest version and confirm it is fixed for you? Thanks
