### ISSUE TITLE
Docker build in lo

### ISSUE THREAD

**Issue by venkateshkumar** [Azure-Samples/chat-with-your-data-solution-accelerator#229]
We are facing the issue  while building the docker image and followed the instructions given below.

We can run the application through the docker compose and   python -m flask --app ./app.py --debug run

mentioned in the following instructions .

https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/LOCAL_DEPLOYMENT.md

![Uploading screenshot_latest.png…]()

**Comment by ross-p-smith** [comment]
Hi @venkateshkumar - can you reupload the picture of the problem you are facing? It appears to have not uploaded,

**Comment by ross-p-smith** [comment]
Closing as the solution no longer uses Docker images
