### ISSUE TITLE
GPT4 support

### ISSUE THREAD

**Issue by venkateshkumar** [Azure-Samples/chat-with-your-data-solution-accelerator#245]
I want to know whether this solution accerlator supports GPT4 when we executed with GPT4 facing some issues.

**Comment by ross-p-smith** [comment]
Hi @venkateshkumar I am running GPT4 - what issues are you having?

**Comment by venkateshkumar** [comment]
we want to understand langchain supports GPT4, as per current repository its integrated with GPT3.5 with langchain
one more observation when we follow the one click deployment we are facing issues in the backend api's
admin part is working fine.

**Comment by ross-p-smith** [comment]
Hi @venkateshkumar 
1) This repo is an accelerator. The idea is that you can take this and change some of the settings like GPT4 and the deploy. You probably have to pick a region that has quota for gpt4. This is documented, try Sweden. You can also change langchain before you deploy
2) Can you describe the issues with the backend apis? What are the symptoms, do you have screenshots/errors/or can you describe what is happening
3) Great to know the admin part is working fine. Are you waiting a while before you upload the files before you use the backend? It can take some time to index the documents

**Comment by venkateshkumar** [comment]
We had quota for Switzerland and configured the gpt4 as input parameter in bicep file.
Need to know whether GPT4 will support Lang chain. There are two strategies mentioned like open ai /langchain.
![MicrosoftTeams-image (21)](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/518724/c272863b-8f94-4408-8a28-c18433a90609)

**Comment by venkateshkumar** [comment]
We have checked the configurations but its throwing an error at backend

**Comment by ross-p-smith** [comment]
Linking #177

**Comment by ross-p-smith** [comment]
@venkateshkumar This repo is using an old version of langchain (I've linked above) and there is a piece of work that we need to do to support a new version. Are you able to use `openai_function` instead of `langchain` as the OrchestrationStrategy? I have just test with gpt4 and openai_function and can ingest and query

**Comment by ross-p-smith** [comment]
The error in the trace talks about a missing `APPINSIGHTS_CONNECTION_STRING`. @venkateshkumar - Are you able to confirm whether this is still an issue for you

**Comment by venkateshkumar** [comment]
We are able to run the accerlator
