### ISSUE TITLE
Naming convention for app components: Frontend, Backend, Admin

### ISSUE THREAD

**Issue by bdleavitt** [Azure-Samples/chat-with-your-data-solution-accelerator#25]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
### Expected/desired behavior
Suggestion for the naming conventions for the pieces of the app. Today it is shown as two main piece:

1. Frontend (which includes the Flask app and the TS React UI) 
2. Backend (which includes the admin app/UI)
3. Batch Processing Functions

For clarity sake, I'd suggest we refer to the "backend" as the "admin" application, as I believe many will conceptualize the main app's Flask component as the "backend" and the react application or UI as the "frontend." Just a naming convention, but would it make sense to organize as:

1. App
    a. Frontend (TS React)
    b. Backend (Flask Application)
2. Admin App (Streamlit)
3. Batch Processing Functions

**Comment by ruoccofabrizio** [comment]
done, thank @bdleavitt
