### ISSUE TITLE
Deployed webapp gives timeout error (getting an answer takes longer than 60 seconds)

### ISSUE THREAD

**Issue by stefvleugels** [Azure-Samples/chat-with-your-data-solution-accelerator#254]
> Please provide us with the following information:
> ---------------------------------------------------------------

Running the app on localhost and asking questions gives an average response time of 10 secods. But when deployed on Azure it often takes more than 1 minute. When a request takes longer than 1 minute an exception is thrown.

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Any log messages given by the failure
An error occurred. Please try again. If the problem persists, please contact the site administrator.

### Expected/desired behavior
A response within 60 seconds, preferably within 20

### Mention any other details that might be useful
Tried different ASP pricing plans, currently running P0v3 which is a little faster than S1 but still around 1 minute.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
Thanks for the feedback - we will look into this for you

**Comment by stefvleugels** [comment]
Seems to only be an issue when using gpt-4. gpt-35-turbo responds withing 10 seconds

**Comment by stefvleugels** [comment]
Seems to only be an issue when using gpt-4. gpt-35-turbo responds withing 10 seconds
