### ISSUE TITLE
failure of event grid #invalid_request

### ISSUE THREAD

**Issue by maurizio-ragusa-gih** [Azure-Samples/chat-with-your-data-solution-accelerator#280]
Hi, 

when i try to deploy the accelerator i have a failure in the doc-processing deployment (see attached screenshot).

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/145765911/ce69fb33-81b2-4cdd-b342-5ec472850458)

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> automatic deploy with ARM template

### Any log messages given by the failure
>
{
  "code": "InvalidRequest",
  "message": "System topic source cannot be modified."
}

### Expected/desired behavior
> successful deployment

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
Thanks for reporting this - the deployment of this accelerator is currently being worked on. Please bear with us whilst we get #281 in and then we will look into this after.

**Comment by ross-p-smith** [comment]
I have just come across this too. I was able to delete the Event Subscription and redeploy. We will investigate why this is not idempotent and keep this open until we fix this
