### ISSUE TITLE
Authentication & Authorization

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/chat-with-your-data-solution-accelerator#282]
> Please provide us with the following information:
> ---------------------------------------------------------------
Hello,

In terms of authentication & authorization of the two front end apps with Entra ID, should they be treated as 1 SPA + 1 Web App? In that case the tenant preparation would be different. Any suggestion or possible solution on this?

Thanks!

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Linux
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
There is a little bit of guidance in the Demo version of this: - https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/README.md#enabling-authentication

**Comment by ross-p-smith** [comment]
Hi @mirojs - we dont plan on adding any AuthN features to the repository - can we close this?
