### ISSUE TITLE
Include GPT-4 V model to be able to search for images and embedding images.

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#323]
# Motivation

Company data often comprises various types of images, including screenshots, maps, and diagrams. By enabling the chat admin app to ingest and process these images, it can provide more accurate and relevant responses to user queries that involve visual data. This ensures that the chat app can fully utilise all available company data to deliver an improved user experience.

Note: Image processing is only available using GPT-4 https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#gpt-4-and-gpt-4-turbo-preview

# How would you feel if this feature request was implemented?

![gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTdtZ3ZmZ29uNWV4dW5zaXZsNjI4ajBkcmRjam1nbmpuMmFteGp0ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HHWdyVKaKJfI8qqJKU/giphy.gif)

# Requirements

- Ensure existing application works correctly with GPT-4
- Allow images to be uploaded via the Admin application
- When "Reprocess all" is click via the Admin app, reprocess the images
- When a question is asked, image data should be searched and passed to `gpt-4-vision` to generate a response
- Citations should link to the image stored in blob storage
- ~**Stretch:** Fallback to OCR/document intelligence if image of a document detected~
- ~**Stretch:** Allow images to be uploaded when chatting~

# Tasks

- [x] #713
- [x] #715
- [x] #728
- [x] #748
- [x] #749
- [x] #750
- [x] #752
- [x] #965
- [ ] #964
- [ ] #993
- [ ] Investigate it's possible to turn advanced image processing on/off without reprovisioning
- [ ] Allow images to be uploaded via pull model (if possible, this indicates it may not be - https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/docs/gpt4v.md#setup-and-usage)

# Bugs

- [x] #929

**Comment by ross-p-smith** [comment]
Reference here: - https://github.com/Azure-Samples/azure-search-openai-demo/pull/1056

**Comment by adamdougal** [comment]
**Update 23rd April:**

- The computer vision and gpt-4-vision model deployment resources are now being provisioned
- This is applied if `USE_GPT4_VISION=true`
- Unfortunately, `gpt-4-vision` does not support function calling, so this is an additional deployment alongside another model
- Next steps are to allow images to be uploaded via the admin app
- It looks like some images are already able to be uploaded and parsed, but computer vision supports additional file types that need to be handled

**Comment by cecheta** [comment]
Update: 28th May

The core tasks relating to this story have been completed, namely uploading images with advanced image processing, and querying data based on these images, passing these to the LLM.

There exist some outstanding tasks regarding updating the prompts to match include the images that are passed to the LLM, and also getting it to work with integrated vectorisation. However, it may be better to move these into their own issues, so this main epic can be closed.

@ross-p-smith @adamdougal @superhindupur
