### ISSUE TITLE
Provide better Guidance on how to get the project working from clean install

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#378]
The guidance on getting the solution working from a clean install is causing confusion and needs to be tidied up.

Fixes: #373 

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Follow the instructions from the main readme.md

**Comment by Lawndemon** [comment]
I second this - I need to be able to use already provisioned resources given the limited regional availability of OpenAI. I'm working on modifying the main.bicepparam file but having an variables file that could be used in place of the environment variables configured during deploy would make this much easier to work with.

**Comment by ross-p-smith** [comment]
@Lawndemon - can I just understand what your requirements are here so I can see if we can address them?
- Do you want to deploy some resources in different regions than others? Can you give an example?
- You want to reuse existing resources? You can do something like `azd env set MY_ENV_KEY value` and that will write it to the default `.env` file. We could then read it in the bicepparams. Is that what you mean?
