### ISSUE TITLE
Auto document indexing fails to run because backend job functions fail to register

### ISSUE THREAD

**Issue by Voileexperiments** [Azure-Samples/chat-with-your-data-solution-accelerator#384]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Open the devcontainer in codespaces, and deploy with `azd deploy` with `authType = keys` and `useKeyVault = false`.

Chatbot web page works fine. I can upload documents from admin functions but cannot get documents to be indexed at all.

After some investigation, I found that the functions failed to register in backend. It's hard to debug because no logs were generated in app stream or app insights (presumably because job functions failed to register). The only logs that exist are from **Functions that are not triggering** tab.

### Any log messages given by the failure
| Exception Type | Total Occurrences | Exception Message | Latest Timestamp
| --- | --- |--- | --- |
| `No job functions found. Try making your job classes and methods ` | `2` | No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.). | 3/7/2024 4:00:42 AM |
| `Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException` | `2` | Worker failed to index functions<br>Result: Failure Exception: TypeError: 'module' object is not callable Stack:   File '/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py', line 348, in _handle__functions_metadata_request     fx_metadata_results = self.index_functions(function_path)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File '/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py', line 633, in index_functions     indexed_functions = loader.index_function_app(function_path)                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File '/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/utils/wrappers.py', line 44, in call     return func(\*args, \*\*kwargs)            ^^^^^^^^^^^^^^^^^^^^^   File '/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/loader.py', line 222, in index_function_app     imported_module = importlib.import_module(module_name)                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File '/usr/local/lib/python3.11/importlib/__init__.py', line 126, in import_module     return _bootstrap._gcd_import(name[level:], package, level)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File '', line 1204, in _gcd_import   File '', line 1176, in _find_and_load   File '', line 1147, in _find_and_load_unlocked   File '', line 690, in _load_unlocked   File '', line 940, in exec_module   File '', line 241, in _call_with_frames_removed   File '/home/site/wwwroot/function_app.py', line 4, in      from BatchStartProcessing import bp_batch_start_processing   File '/home/site/wwwroot/BatchStartProcessing.py', line 11, in      env_helper: EnvHelper = EnvHelper()                             ^^^^^^^^^^^  | 3/7/2024 4:00:39 AM |

### Expected/desired behavior
Job functions should register without error

### OS and Version?
N/A

### Versions
latest

### Mention any other details that might be useful

**Comment by joshrenshaw12** [comment]
this could be fixed after merge of #388 
in my testing I found that the functions were not being created as there were errors within the code.
once all errors were rectified functions were deployed into Azure successfully.
