### ISSUE TITLE
ResourceNotFoundError after changing to "rbac"

### ISSUE THREAD

**Issue by yutaoc137** [Azure-Samples/chat-with-your-data-solution-accelerator#385]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Changed AZURE_AUTH_TYPE="rbac" and USE_KEY_VAULT="false"
then ran azd up, no error during deployment, but have error chatting through the webapp

### Any log messages given by the failure
>
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/tmp/8dc3e4799ba4ee3/backend/batch/utilities/tools/ContentSafetyChecker.py", line 48, in _filter_text_and_replace
    response = self.content_safety_client.analyze_text(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/8dc3e4799ba4ee3/antenv/lib/python3.11/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
   return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
   File "/tmp/8dc3e4799ba4ee3/antenv/lib/python3.11/site-packages/azure/ai/contentsafety/_operations/_operations.py", line 431, in analyze_text
     map_error(status_code=response.status_code, response=response, error_map=error_map)
   File "/tmp/8dc3e4799ba4ee3/antenv/lib/python3.11/site-packages/azure/core/exceptions.py", line 164, in map_error
     raise error
 azure.core.exceptions.ResourceNotFoundError: (ResourceNotFound) Subdomain does not map to a resource.
 Code: ResourceNotFound
 Message: Subdomain does not map to a resource.

### Expected/desired behavior
>No errors thrown before change:
Authenticate using RBAC instead of API Keys

### OS and Version?
> macOS (Sonoma)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by komalg1** [comment]
Hi @yutaoc137, I am not able to reproduce this issue. In case you still see issue you can  follow this [guide](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/LOCAL_DEPLOYMENT.md#authenticate-using-rbac)
