### ISSUE TITLE
'EnvHelper' object has no attribute 'AZURE_KEY_VAULT_ENDPOINT'

### ISSUE THREAD

**Issue by jtejeroc** [Azure-Samples/chat-with-your-data-solution-accelerator#387]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Launch accelerator from devcontainer.
2. Upload document in "Ingest Data" tab from Admin page.

### Any log messages given by the failure
> Traceback (most recent call last): File "/tmp/8dc3e97a2013125/pages/01_Ingest_Data.py", line 204, in <module> upload_file(bytes_data, up.name) File "/tmp/8dc3e97a2013125/pages/01_Ingest_Data.py", line 146, in upload_file env_helper.AZURE_KEY_VAULT_ENDPOINT, credential ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'EnvHelper' object has no attribute 'AZURE_KEY_VAULT_ENDPOINT'

![error](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/156185749/a3cc727b-5ffe-4311-8231-cd4298fb7c26)

### Expected/desired behavior
> Upload document to Azure Blob Storage successfully and create embeddings.

### OS and Version?
> Windows 10 Pro 22H2

### Versions
> Latest version of accelerator.

### Mention any other details that might be useful
EnvHelper class does not seem to have defined the `AZURE_KEY_VAULT_ENDPOINT` attribute rather than using the environment variable to create `self.secret_client` attribute (line 90-92), not `self.AZURE_KEY_VAULT_ENDPOINT`.
However, `01_Ingest_data.py` (line 145-147) tries to define again both `credential` and `secret_client` using `env_helper.AZURE_KEY_VAULT_ENDPOINT` (not existing) instead of directly defining `secret_client = env_helper.secret_client`.

![EnvHelper](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/156185749/c636b380-7e71-4bb4-801b-165604eb5ed6)
![01_Ingest_data](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/156185749/2f97080d-55f3-46dc-99d7-68ca7ac3fd71)

## Proposal update:
Instead of just changing that single line, I think it is needed to completely change lines 143-152 to just `account_key=env_helper.AZURE_BLOB_ACCOUNT_KEY` as the rest of the process is already performed during env_helper creation. I did it and the document was uploaded to Azure Blob Storage successfully.

![01_Ingest_data_changes](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/156185749/6192dcad-a6e4-4207-a24d-9a69329aaab7)

**Comment by sreedharguda** [comment]
Hi @leonavevor I am also facing the same issue, does this issue resolved, if yes please help me the changes you made it to resolve. thank you.

**Comment by sreedharguda** [comment]
Hi @ross-p-smith @leonavevor , if we wanted to ingest the CSV or excel file, where we have to change in the code base. Please suggest me. Thank you.
