### ISSUE TITLE
Not able to see the uploaded documents in delete_data and explore_data section in admin webpage

### ISSUE THREAD

**Issue by PFA23SCM89S** [Azure-Samples/chat-with-your-data-solution-accelerator#389]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Not able to see the uploaded documents in delete_data and explore_data  in admin webpage. Im also not able to add url. Im able to see the uploaded documents in backend but not in these sections

### Any log messages given by the failure
>
<img width="1235" alt="Screen Shot 2024-03-10 at 4 14 23 PM" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/124114584/9c39f14f-3cf2-4853-895d-a461153414b1">
<img width="1279" alt="Screen Shot 2024-03-10 at 4 13 47 PM" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/124114584/a9fd7907-0f13-4559-835e-7e54b4ef13e1">
<img width="1275" alt="Screen Shot 2024-03-10 at 4 13 37 PM" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/124114584/deaf4196-bae0-4bed-a218-6d1ee61ef1d1">
<img width="1300" alt="Screen Shot 2024-03-10 at 4 13 23 PM" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/124114584/6283d71b-32c6-4e2a-a2bd-31a4145f7dd5">

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ross-p-smith** [comment]
Hi @PFA23SCM89S - There are 2 errors here.
1) When you upload a url - it needs to be an html file, you have pointed the page at itself
2) When you upload a file - could it have just taken a longer time - did it eventually embed the file from storage? Were there any errors in the Function App?

**Comment by ross-p-smith** [comment]
Hi @PFA23SCM89S - I am going to close this issue this week without a response. Are you able to respond?
