### ISSUE TITLE
Some answers might be coming from the internet 

### ISSUE THREAD

**Issue by blessing-msft** [Azure-Samples/chat-with-your-data-solution-accelerator#39]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I asked when Microsoft was founded and was told 1975 with a reference to the 10k Then I asked again and this time was told a specific date April 4, 1975. But this date does not appear in any of our sample data docs.

### Any log messages given by the failure
>
![image](https://github.com/Azure-Samples/azure-search-openai-solution-accelerator/assets/126516323/579e433b-0ba1-4193-8be9-246cb3d344f9)

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Updated prompt accordingly.
