### ISSUE TITLE
OpenAI On Your Data skill ignores custom metadata field

### ISSUE THREAD

**Issue by JakobStadlhuber** [Azure-Samples/chat-with-your-data-solution-accelerator#391]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

1. setup bring your own data with the Azure Playground to create the indexes, indexer, skill... based on a blob storage
2. add a custom field with the same name as the blob storage files meta data field in both new created indexes 
3. modify the created skill by adding the needed custom field
4. the [preprocessing-jobs](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/use-your-data-securely#data-ingestion-architecture) api (used in the skill) does ignore the custom field and does not create it in the resulting chunk.json

### Expected/desired behavior
both indexes that are created with the OpenAI Playground should contain the custom metadata field from the file in the blob storage.

**Comment by ross-p-smith** [comment]
Is this the same as #251?

**Comment by JakobStadlhuber** [comment]
> Is this the same as #251?

no its not releated

**Comment by reechamishra** [comment]
@reechamishra  to investigate if this is related to this repo ?

**Comment by reechamishra** [comment]
@JakobStadlhuber Before we pick this item to work on this , can you confirm this issue is related to the code with this particular accelerator "Chat with your data" ?

**Comment by ross-p-smith** [comment]
@JakobStadlhuber - I am closing this as the description talks about "On Your Data" and the OpenAI playground which is not this repository. Please re-open if I have closed incorrectly
