### ISSUE TITLE
Use async framework, not Flask

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/chat-with-your-data-solution-accelerator#40]
# Motivation

See my blog post here:
http://blog.pamelafox.org/2023/09/best-practices-for-openai-chat-apps.html

We ported the other sample to Quart, as it was a more 1:1 mapping from Flask, but the more popular async framework is FastAPI.

Such a change will enable users to handle more requests with less resources / lower SKUs.

# How would you feel if this feature request was implemented?

![efficient](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2M2MGQwNWZ6OHN5cmJ1cG5haTQwdXltZ25hdGgyMjBzNHVsZjhtOCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/GY9nnHFeqGhU1awm0k/giphy.gif)

# Requirements

- Switch to a more efficient application framework

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ashikns** [comment]
Question: The docker files use `uWSGI`, wouldn't that already support parallelism? At least in terms of parallel users.

**Comment by pamelafox** [comment]
@ashikns Yes, you can have multiple workers/threads when running a WSGI app using gunicorn on a multi-core machine. However, if all those workers are tied up waiting for the results of an API call, they can't respond to new user requests. With async calls and frameworks, a worker can service a new request while waiting for the results. You can serve more users with less cores.
