### ISSUE TITLE
Use managed identity, not keys

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/chat-with-your-data-solution-accelerator#41]
app.py currently uses keys, not managed identity. Best practice for enterprises is to use identity tokens. See my blog post here:

http://blog.pamelafox.org/2023/09/best-practices-for-openai-chat-apps-go.html

Unfortunately, the dataSources API doesn't yet support managed identity, but we're told the change is coming soon.

**Comment by gmndrg** [comment]
@komalg1 Absolutely! Please go ahead!

**Comment by ross-p-smith** [comment]
Komal, can you list all the different parts that will be needed to close this issue?

For instance
- [ ] #90
