### ISSUE TITLE
Handle BlobDeleted events from Event Grid

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#414]
# Describe the bug
The EventGrid topic sends messages to the Storage queue both when a blob is created or deleted, however the `batch_push_results` function is set up to only handle blob created items. When an item is deleted from the storage container, the corresponding message in the queue ends up in the poison queue, as it cannot be processed.

# Expected behavior
One of the following:
* The Azure function does not respond to delete events
* The function handles delete events appropriately, e.g. also deletes from Azure Search (this point would need further discussion)

---

# Debugging information

## Steps to reproduce
1. Upload item to storage container (it should be processed successfully)
2. Delete item from storage container
3. View `batch_push_results` Azure function logs
4. View `doc-processing-poison` queue

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/60179183/7bba7abf-93aa-4753-897c-d33216d482de)

## Logs

If applicable, add logs to help the engineer debug the problem.

```
2024-03-12T10:17:57Z   [Error]   Error adding embeddings for https://*********.blob.core.windows.net/documents/PressReleaseFY23Q4.docx?*******************: File is not a zip file
```

---

# Tasks

_To be filled in by the engineer picking up the issue_

**Comment by adamdougal** [comment]
As part of this we should probably move the deleting from the index from the admin app to the function. That way we can delete from storage without using the admin app, in the same way we can add documents to blob storage directly without using the admin app.

**Comment by matthieugi** [comment]
I like the idea of moving the business logic to the function. Did somebody start to work on this ?

**Comment by ross-p-smith** [comment]
Nobody is working on this - please feel free to take it . . .
