### ISSUE TITLE
Response types have wrong mime-type

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/chat-with-your-data-solution-accelerator#42]
Response currently has "event/stream" which is the mime-type for SSE, but the response is not SSE - it's a streaming HTTP response using Transfer-Encoding: chunked.

I agree with the choice of response type (as I detail in my blog post @ http://blog.pamelafox.org/2023/08/fetching-json-over-streaming-http.html ), but the mime-type should be changed. I think it can simply be dropped entirely.

Right now, the browser shows an Event Source tab, thinking that SSE events are coming in, and then none come in. If you make the change, you should be able to see the response come in correctly with no Event Source tab in Developer Tools.

**Comment by ross-p-smith** [comment]
Hey @cecheta - can you have a look at this comment and align the two codebases? https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/189#issuecomment-1893952810 - thanks
