### ISSUE TITLE
Add credential scanning to the build so that secrets are not part of the commit history

### ISSUE THREAD

**Issue by adamdougal** [Azure-Samples/chat-with-your-data-solution-accelerator#421]
# Motivation

To ensure no credentials are accidentally stored to the repo.

# How would you feel if this feature request was implemented?

![secret](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExd3l1dThhOGhsaHZ5cm01NjJrejAzZnRmbXk0N3R3cTkya3N1aGk3YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/hj8eOHrXqoLntsCyWz/giphy.gif)

# Requirements

- Scan for credentials as part of PR requests
- The PR build should fail if credentials are detected

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
All repositories in the `Azure-Samples` org have the following turned on by default
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/6254153/e2772505-ffd9-4193-ac88-b870c0b63046)
This is not achieved at push though

**Comment by ross-p-smith** [comment]
Through the Sprint champion we have this down to zero now 
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/6254153/0e5fb7a0-be0e-4c81-8cc6-db910877bf33)
