### ISSUE TITLE
Any plans to expand this solution for PPT, CSV and Excel files to ingrest and do for comparion of tabs in the excel/csv sheet

### ISSUE THREAD

**Issue by sreedharguda** [Azure-Samples/chat-with-your-data-solution-accelerator#425]
# Motivation

A clear and concise description of why this feature would be useful and the value it would bring. 
Explain any alternatives considered and why they are not sufficient.

# How would you feel if this feature request was implemented?

_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

# Requirements

A list of requirements to consider this feature delivered
- Requirement 1
- Requirement 2
- ...

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
#106 is currently being looked at. We will investigate the other file formats and get back to you. Many thanks for the question!

**Comment by adamdougal** [comment]
I've just created an issue for Excel + CSV here https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/issues/659.

Closing this issue in favour of those linked above.
