### ISSUE TITLE
Bug - Deploy is all SUCCESS but the admin site for ingest does not launch

### ISSUE THREAD

**Issue by robert-kirstenpipe** [Azure-Samples/chat-with-your-data-solution-accelerator#429]
# Describe the bug
My desktop deployment via VS Code and Terminal finished all green and success. However when finished only the chat web URL would launch and work. The admin URL does not launch and says :( Application Error.

# Expected behavior
Both web URLs launch and work properly.

# How does this bug make you feel?
Like the repo is broken

---

# Debugging information

## Steps to reproduce
1. Download ZIP of the MAIN repo
2. Unpack to local desktop
3. Follow README instructions for deployment including local Docker desktop and azd up to deploy everything
4. Wait 46 mins and see a fully green log that everything succeeded
5. Browse to the Resource Group that was created
6. Launch the Q&A web site ... loads fine
7. Launch the ADMIN web site ... error as per screenshot below

## Screenshots
Error when launching the admin site:
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/156730677/87fa1ac5-f70e-43ae-80cc-f4bf9bb9989e)

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/156730677/da0610c2-e0ef-4d24-832b-1e5b072bdd49)

## Logs
 ➜ /workspaces/chat-with-your-data-solution-accelerator-main $ azd up

Packaging services (azd package)

  (✓) Done: Packaging service adminweb
  - Package Output: /tmp/chat-with-your-data-solution-accelerator-adminweb-azddeploy-1710358670.zip

  (✓) Done: Packaging service function
  - Package Output: /tmp/chat-with-your-data-solution-accelerator-function-azddeploy-1710358671.zip

  |=      | Packaging service web(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed
  |==     | Packaging service web(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed
  |===    | Packaging service web(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠏ idealTree: timing idealTree Completed
  |====   | Packaging service web(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠼ idealTree: timing idealTree Completed
  |=====  | Packaging service web(##################) ⠋ reify:@esbuild/android-arm: timing re

up to date, audited 277 packages in 979ms

108 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
  |====== | Packaging service web
> frontend@0.0.0 build
> tsc && vite build

  |       | Packaging service webvite v4.5.2 building for production...
✓ 2821 modules transformed.
../static/index.html                           0.45 kB │ gzip:   0.30 kB
../static/assets/mic-outline-c1720523.svg      0.89 kB │ gzip:   0.48 kB
../static/assets/Send-d0601aaa.svg             0.92 kB │ gzip:   0.54 kB
../static/assets/Azure-30d5e7c0.svg            2.04 kB │ gzip:   0.84 kB
../static/assets/index-32bee7ea.css           10.19 kB │ gzip:   2.32 kB
../static/assets/index-1de35061.js         1,334.28 kB │ gzip: 367.44 kB │ map: 8,356.46 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 1m 33s
  (✓) Done: Packaging service web
  - Package Output: /tmp/chat-with-your-data-solution-accelerator-web-azddeploy-1710359455.zip

SUCCESS: Your application was packaged for Azure in 13 minutes 12 seconds.

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: Microsoft Azure Sponsorship 2 (19b29b25-a38c-443f-bc1f-e0aaf8e55116)
Location: East US

  You can view detailed progress in the Azure Portal:
  https://portal.azure.com/#view/HubsExtension/DeploymentDetailsBlade/~/overview/id/%2Fsubscriptions%2F19b29b25-a38c-443f-bc1f-e0aaf8e55116%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2Fcwyd-qa-20240313-1710359465

  (✓) Done: Resource group: rg-cwyd-qa-20240313
  (✓) Done: Cognitive Service: cwyd-qa-20240313-contentsafety-usbdjslzxh3f2
  (✓) Done: Log Analytics workspace: cwyd-qa-20240313-logAnalytics-usbdjslzxh3f2
  (✓) Done: Cognitive Service: cwyd-qa-20240313-speechservice-usbdjslzxh3f2
  (✓) Done: App Service plan: cwyd-qa-20240313-hosting-plan-usbdjslzxh3f2
  (✓) Done: Application Insights: cwyd-qa-20240313-appinsights-usbdjslzxh3f2
  (✓) Done: Portal dashboard: dash-cwyd-qa-20240313-appinsights-usbdjslzxh3f2
  (✓) Done: Storage account: strusbdjslzxh3f2
  (✓) Done: Key Vault: kv-usbdjslzxh3f2
  (✓) Done: Document Intelligence: cwyd-qa-20240313-formrecog-usbdjslzxh3f2
  (✓) Done: Azure OpenAI: cwyd-qa-20240313-openai-usbdjslzxh3f2
  (✓) Done: Search service: cwyd-qa-20240313-search-usbdjslzxh3f2
  (✓) Done: App Service: cwyd-qa-20240313-website-usbdjslzxh3f2-admin
  (✓) Done: App Service: cwyd-qa-20240313-website-usbdjslzxh3f2
  (✓) Done: Function App: cwyd-qa-20240313-backend-usbdjslzxh3f2

SUCCESS: Your application was provisioned in Azure in 17 minutes 31 seconds.
You can view the resources created under the resource group rg-cwyd-qa-20240313 in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/19b29b25-a38c-443f-bc1f-e0aaf8e55116/resourceGroups/rg-cwyd-qa-20240313/overview

Deploying services (azd deploy)

  (✓) Done: Deploying service adminweb
  - Endpoint: https://cwyd-qa-20240313-website-usbdjslzxh3f2-admin.azurewebsites.net/

  (✓) Done: Deploying service function
  - Endpoint: https://cwyd-qa-20240313-backend-usbdjslzxh3f2.azurewebsites.net/

  (✓) Done: Deploying service web
  - Endpoint: https://cwyd-qa-20240313-website-usbdjslzxh3f2.azurewebsites.net/

SUCCESS: Your application was deployed to Azure in 15 minutes 20 seconds.
You can view the resources created under the resource group rg-cwyd-qa-20240313 in Azure Portal:
https://portal.azure.com/#@/resource/subscriptions/19b29b25-a38c-443f-bc1f-e0aaf8e55116/resourceGroups/rg-cwyd-qa-20240313/overview

SUCCESS: Your up workflow to provision and deploy to Azure completed in 46 minutes 4 seconds.

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
Thanks @robert-kirstenpipe - are you able to give me those two logs in that last screen shot?

If you ever want to deploy just that step - you can try `azd deploy adminweb`

**Comment by robert-kirstenpipe** [comment]
This might be the culprit?

[A screenshot of a computer program  Description automatically generated]

This seems to say I need Python 3.11.8?  I checked and my Windows 11 has Python 3.12.

The other says this:

Cleaning up temp folders from previous zip deployments and extracting pushed zip file /tmp/zipdeploy/9a74cfa8-28ee-491c-9efb-5a46666593c0.zip (0.06 MB) to /tmp/zipdeploy/extracted

**Comment by Lawndemon** [comment]
I have this problem for both the admin and main websites. The project deploys fine but neither site loads. The deployment seems to have worked and the app is registered into a deployment slot:
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/40279697/6df297f7-4370-4d24-912c-72adcad0d442)
I had to customize the deployment of OpenAI due to regional availability so it is running in canadaeast while everything else is in canadacentral so perhaps this is part of the problem?

I can confirm that the app deployed with no errors and has been published/registered to a deployment slot. Happy to provide any other information that might help.

**Comment by ross-p-smith** [comment]
Hi @Lawndemon, there are a few places I would check to see what is occurring.
1) Does the Admin Site render?
2) When you upload a file from the admin site, do you see it sat in the storage account?
3) Is the FunctionApp running? Has there been a problem picking up that file?
4) If you go to the "Explore" page in the Admin app - are any files listed?

**Comment by nawangwe** [comment]
I am facing this issue as well. Did not change anything in the source. All I did was run azd up. Deployment was a success, but I get the same error.

This is my app service log:

> 2024-03-15T06:32:17.583281533Z    _____                               
2024-03-15T06:32:17.583314633Z   /  _  \ __________ _________   ____  
2024-03-15T06:32:17.583319633Z  /  /_\  \\___   /  |  \_  __ \_/ __ \ 
2024-03-15T06:32:17.583323733Z /    |    \/    /|  |  /|  | \/\  ___/ 
2024-03-15T06:32:17.583327533Z \____|__  /_____ \____/ |__|    \___  >
2024-03-15T06:32:17.583331733Z         \/      \/                  \/ 
2024-03-15T06:32:17.583335433Z A P P   S E R V I C E   O N   L I N U X
2024-03-15T06:32:17.583356933Z 
2024-03-15T06:32:17.583360833Z Documentation: http://aka.ms/webapp-linux
2024-03-15T06:32:17.583364733Z Python 3.11.7
2024-03-15T06:32:17.583368634Z Note: Any data outside '/home' is not persisted
2024-03-15T06:32:18.350948973Z Starting OpenBSD Secure Shell server: sshd.
2024-03-15T06:32:18.421965682Z Site's appCommandLine: python -m streamlit run Admin.py --server.port 8000 --server.address 0.0.0.0 --server.enableXsrfProtection false
2024-03-15T06:32:18.421998282Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite -userStartupCommand 'python -m streamlit run Admin.py --server.port 8000 --server.address 0.0.0.0 --server.enableXsrfProtection false'
2024-03-15T06:32:18.443997278Z Could not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
2024-03-15T06:32:18.444034778Z Could not find operation ID in manifest. Generating an operation id...
2024-03-15T06:32:18.444041378Z Build Operation ID: f446c31b-7a3b-4e4c-8cf7-8c97d7152fff
2024-03-15T06:32:18.948001969Z Oryx Version: 0.2.20240127.1, Commit: 4b7f2dffcc69c214f9806d67a85ec8926e2393e1, ReleaseTagName: 20240127.1
2024-03-15T06:32:19.040623072Z Writing output script to '/opt/startup/startup.sh'
2024-03-15T06:32:19.175744659Z WARNING: Could not find virtual environment directory /home/site/wwwroot/antenv.
2024-03-15T06:32:19.175781059Z WARNING: Could not find package directory /home/site/wwwroot/__oryx_packages__.
2024-03-15T06:32:19.241664845Z /opt/python/3/bin/python: No module named streamlit

**Comment by nawangwe** [comment]
> Thanks @robert-kirstenpipe - are you able to give me those two logs in that last screen shot?
> 
> If you ever want to deploy just that step - you can try `azd deploy adminweb`

Running `azd deploy adminweb` after the initial deployment and restarting the app service fixed it for me.

**Comment by robert-kirstenpipe** [comment]
I just tried and this "azd deploy adminweb" also worked to repair my deployment.

So two things ...

1.
How will a random user know to do this?

2.
What is the underlying root cause that is causing this for users in the first place ... and can we remedy this? Especially when the deployment shows all green success messages?

Thanks all !
BobT

**Comment by chrisbaudo** [comment]
> > Thanks @robert-kirstenpipe - are you able to give me those two logs in that last screen shot?
> > If you ever want to deploy just that step - you can try `azd deploy adminweb`
> 
> Running `azd deploy adminweb` after the initial deployment and restarting the app service fixed it for me.

Ditto.  I observed the same behavior.  The initial deployment does not seem to work, but running 'azd deploy adminweb' again fixes the issue.

**Comment by Lawndemon** [comment]
> Hi @Lawndemon, there are a few places I would check to see what is occurring.
> 
> 1. Does the Admin Site render?
... Yes it renders now and all the tabs load. The fix seemed to be a simple stop --> start of the app in Azure
> 2. When you upload a file from the admin site, do you see it sat in the storage account?
... No, this process doesn't work. However, I dropped a file directly into the blob container via the Azure Portal and it seems like the chunking process executed correctly so I'm thinking it may be something to do with the Flask App. Maybe CORS?
> 3. Is the FunctionApp running? Has there been a problem picking up that file?
... Yep all three FunctionApps are registered and show as running. No issues with deployment either. That being said, the main app doesn't work and errors out with every prompt entry. This may be due to some challenges I'm having with content_safety so I won't call it a bug until I troubleshoot a bit more
> 4. If you go to the "Explore" page in the Admin app - are any files listed?
... Yes but only the one that I manually added to the blob store. None of the files I've attempted to add via the import pane show up. Also, I've attempted to import a URL and get an orchestration error

**Comment by ross-p-smith** [comment]
There is a new deployment mechanism which will use pre-built containers to speed this up as the Oryx build is very slow. I'd be interested if @Lawndemon, @chrisbaudo, @robert-kirstenpipe, @nawangwe use this repo as a demo or you change code and deploy manually to app service. This will help me invest time in the right area.

**Comment by chrisbaudo** [comment]
Customers and I usually deploy manually from VS Code to App Service.  Honestly, most customers use this repo (and others Microsoft has) as a starter for development and then on to full production.

**Comment by cecheta** [comment]
I believe this issue is due to two things: The build fails due to Oryx, and azd is unable to correctly determine the status of the deployment. Regarding azd, there have already been some issues raised related to this:

* https://github.com/Azure/azure-dev/issues/2669
* https://github.com/Azure/azure-dev/issues/3260
* https://github.com/Azure/azure-dev/issues/3698

If it occurs again, I would recommend raising a bug in the Oryx repo, https://github.com/microsoft/Oryx, providing as much information and logs as possible.

As previously mentioned, the current workaround is to re-deploy the Admin app with `azd deploy adminweb`.

**Comment by ross-p-smith** [comment]
I'm going to close this bug as it's Oryx related.
