### ISSUE TITLE
Enable Semantic Search - after deployment from devcontainer

### ISSUE THREAD

**Issue by cherifbenham** [Azure-Samples/chat-with-your-data-solution-accelerator#449]
# Motivation

It seems like adding a semantic configuration in the Search Index (documents) does not impact the chat/web experience.
I created new Env Variables in Functions Apps resource: AZURE_SEARCH_USE_SEMANTIC_SEARCH=true and AZURE_SEARCH_SEMANTIC_SEARCH_CONFIG=default where there is a semantic configuration in search named 'default'
But search remains as in deployment initial conditions. Please advise

# How would you feel if this feature request was implemented?

Amazing

# Requirements

- Search functions are not impacted by a change in TOP_K or by SEMANTIC_CONFIG

# Tasks

_To be filled in by the engineer picking up the issue_

- Update Search Instances so that they take into account TOP_K and SEMANTIC_CONFIG
- Ideally, add a filter parameter in search

**Comment by ross-p-smith** [comment]
This looks like this is not wired up correctly in the bicep files. There is a `azureSearchUseSemanticSearch` flag which defaults to false, but it never gets passed into `/workspaces/chat-with-your-data-solution-accelerator/infra/core/search/search-services.bicep` so it's always disabled.

**Comment by cherifbenham** [comment]
Thanks Ross for your prompt response, I guess I should also change code/backend/batch/tools/QuestionAnswerTool.py from sources = self.vector_store.similarity_search(query=question, k=4, search_type="hybrid")
to 
sources = self.vector_store.similarity_search(query=question, k=env_helper.TOP_K, search_type="semantic") ?

Any other changes I should implement ?

**Comment by cherifbenham** [comment]
hi @ross-p-smith 

when trying to modify bicep file search-services.bicep from 
param semanticSearch=disabled to 
param semanticSearch=enabled I receive this error message -- any idea how to solve?

failed to save 'search-services.bicep': Unable to write file 'vscode-remote://dev-container+7b227265706f7369746f727950617468223a2268747470733a2f2f6769746875622e636f6d2f617a7572652d73616d706c65732f636861742d776974682d796f75722d646174612d736f6c7574696f6e2d616363656c657261746f72222c22766f6c756d654e616d65223a225f5f554e495155455f5f222c22666f6c646572223a22636861742d776974682d796f75722d646174612d736f6c7574696f6e2d616363656c657261746f72222c22636c6f6e65496e666f223a7b2275726c546f436c6f6e65223a2268747470733a2f2f6769746875622e636f6d2f617a7572652d73616d706c65732f636861742d776974682d796f75722d646174612d736f6c7574696f6e2d616363656c657261746f72227d2c22696e7370656374566f6c756d65223a66616c73657d/workspaces/chat-with-your-data-solution-accelerator/infra/core/search/search-services.bicep' (Canceled: Canceled)
