### ISSUE TITLE
Upgrade Azure functions to use v2 programming model

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/chat-with-your-data-solution-accelerator#46]
From a quick look, it seems like the functions aren't yet using the new programming model, which we want everyone to move towards eventually.

Blog post here:
https://techcommunity.microsoft.com/t5/azure-compute-blog/azure-functions-v2-python-programming-model-is-generally/ba-p/3827474

**Comment by ruoccofabrizio** [comment]
done @pamelafox
