### ISSUE TITLE
Determine if current web app works for non-English Speech input like German , French, swiss German 

### ISSUE THREAD

**Issue by reechamishra** [Azure-Samples/chat-with-your-data-solution-accelerator#473]
**Motivation** 
To determine if web app can support non-English  Language in current version

**Comment by Carcamo-ben** [comment]
It usually responds in the language it is asked. You can modify the template to actually do it as a must.

**Comment by superhindupur** [comment]
I was able to test this with the help of Ren Silva (thanks Ren!). The findings are as follows:

- The current web app supports speech input for English.
- It doesn't support speech input for any non-English language. 
- Any support for non-english languages require explicit configuration in the frontend code. 
- The current web app doesn't consistently respond in the language it is asked. This might require a change of prompt. 
- This work has been added to #317 and will hopefully be picked up later this week.

**Comment by superhindupur** [comment]
This issue can be closed now since the investigation is completed.
