### ISSUE TITLE
Deployment fails with "The account type 'ContentSafety' is either invalid or unavailable in given region."

### ISSUE THREAD

**Issue by agazzeri** [Azure-Samples/chat-with-your-data-solution-accelerator#48]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Start deploying a custom deployment with "Build your own template in the editor".
2. Copy the template from https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/infrastructure/deployment.json
3. Set the required parameters
4. Validate step fails with the following error: 
{
  "code": "InvalidTemplateDeployment",
  "details": [
    {
      "code": "InvalidApiSetId",
      "message": "The account type 'ContentSafety' is either invalid or unavailable in given region."
    }
  ],
  "message": "The template deployment 'Microsoft.Template-20231019202539' is not valid according to the validation procedure. The tracking id is '51f356dd-67f6-47a5-af7e-586ae02a3cf1'. See inner errors for details."
}

Note that I tried multiple regions where Content Safety is available (Canada East, West Europe) and the error is the same.

### Any log messages given by the failure
>

### Expected/desired behavior
>
Deployment succeeds.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Thank you for reporting this! We will be triaging and making the respective fix accordingly.

**Comment by LorenzoRep** [comment]
The creation script creates the resource group in the region specified the first time. Regardless of if the deployment fails (because of selection of a region where the Content Safety service is unavailable), the resource group is created in that region. This seems to cause the issue. Removing the resource group and selecting a region where the Content Safety service is available, solved the problem for me.
