### ISSUE TITLE
Web chat error for all user input --- Included the resolution in the details section.

### ISSUE THREAD

**Issue by hunterjam** [Azure-Samples/chat-with-your-data-solution-accelerator#50]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1. Open the web chat (https://<resource prefix>-website.azurewebsites.net/)
2. Type any message and send.
3. Receive the following message:
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/31451884/9ed64c9a-26ee-4933-ad9f-6a1eab452c54)

### Any log messages given by the failure
> Debugging locally, I was able to gather the following error message:
"error": "No connection adapters were found for '<resource prefix>-contentsafety/contentsafety/text:analyze?api-version=2023-04-30-preview'"'

### Expected/desired behavior
> A valid response from the server.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 11
### Versions
>

### Mention any other details that might be useful
I was able to debug and determine the problem. The AZURE_CONTENT_SAFETY_ENDPOINT within the bicep file (and ARM template) is set to **ContentSafetyName**. 
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/31451884/3fa7d48f-0878-4f3c-82c2-e8ddc2f7c3b8)
It should be set to the following: 'https://${Location}.api.cognitive.microsoft.com/'
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/31451884/b81d9aab-332b-4aaa-9271-2c6c58e89b0e)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ruoccofabrizio** [comment]
Thanks @hunterjam Fixed in fbe036f
