### ISSUE TITLE
Create initial e2e API tests for the chat and admin apps - testing the unmocked system at the API level. 

### ISSUE THREAD

**Issue by superhindupur** [Azure-Samples/chat-with-your-data-solution-accelerator#512]
# Motivation

Under this issue we want to add API-level e2e tests for the admin and chat apps. 

Rationale: In addition to the UI tests added in #419, we need tests that test at the API level. This is because UI tests tend to be flaky/slow and cannot cover all scenarios. We expect the API test suite to be more extensive, and cover almost all API level interactions that are possible with CWYD, without any mocked dependencies. 

# How would you feel if this feature request was implemented?
Confident!

![confident](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExbXgycnVncGsxdXlpejk1aDh6Z3dreDBjYm9oczJvNzV2bmRicnpjcCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o751YGCbwUc8nzcHe/giphy-downsized-large.gif)

# Requirements

- For this issue, the requirement is to cover the backend api testing for  the endpoint /api/conversation/custom and for the admin app to ingest a document.
- There should be an approval workflow so that these tests can run against PRs from forks if allowed by a maintainer of the repo. 

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
This would be a great feature if we had time - closing down for now
