### ISSUE TITLE
Make all filenames PEP8 compliant

### ISSUE THREAD

**Issue by tanya-borisova** [Azure-Samples/chat-with-your-data-solution-accelerator#514]
# Motivation

Make all file names (= module names) consistent with PEP 8, as some file names currently use snake_case, while others use camelCase.

# How would you feel if this feature request was implemented?

_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

![Cleaning up](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXZ0ZTgxMWRpcHVoaXh4ZWo1eTJjazNkbGsybzE3bGVtaXRnYTNubyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cO9GVZKRIov75COLNb/giphy.gif)

- [x] #840 
- [x] #841 
- [x] #864

**Comment by gaurarpit** [comment]
I can pick this up @ross-p-smith
