### ISSUE TITLE
Ensure that Application Insights works from a container running the application code

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#551]
We deploy the code base either as code or container. Make sure that we get telemetry through the application, through the container and into AppInsights

**Comment by adamdougal** [comment]
Confirmed that this works in both a code based deployment and a container based deployment:

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/1589887/851071e2-a712-4791-9334-2e079acbbdfd)
