### ISSUE TITLE
Change `azureOpenAIStopSequence` default value

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#559]
# Motivation

The Bicep param `azureOpenAIStopSequence` has a default of `\n`. This means that any response that contains a new line will immediately be halted, and the full answer will not be returned.

# How would you feel if this feature request was implemented?

👍 

# Requirements

A list of requirements to consider this feature delivered
- Change stop sequence to something more appropriate

# Tasks

_To be filled in by the engineer picking up the issue_

**Comment by komalg1** [comment]
@cecheta Is it not okay to have a new line as the stop sequence? In case anyone wants to customize it based on their needs can update the stop sequence as per need. Isn't it ok to have a new line as stop sequence as a guidance for this repository? Let me know your thoughts

**Comment by cecheta** [comment]
> @cecheta In case anyone wants to customize it based on their needs can update the stop sequence as per need. Isn't it ok to have a new line as stop sequence as a guidance for this repository? Let me know your thoughts

@komalg1 When testing the BYOD endpoint locally, I quite often ran into incomplete responses, and it took me a while to realise that it was due to the stop sequence. New line characters are quite common in any question like "list me the advantages of ...". Personally, I don't think any value should be set by default for this variable, and users can set their own value if they need to. Also, we currently aren't using the stop sequence on the custom endpoint at all.

Additionally, I've noticed a bug, which is that the stop sequence isn't used at all when deployed to Azure, as it looks like environment variables are "trimmed" in Azure, When this is deployed to Azure, `AZURE_OPENAI_STOP_SEQUENCE` is `""`, even though it's set to `\n` in our code.

**Comment by Roopan-Microsoft** [comment]
Hi @cecheta - As we see the Stop Sequence is not used post deployment, can we change the default value to empty in Bicep? Let me know your thoughts.

<img width="263" alt="image" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/168007406/4f987cb4-f5d8-42b6-8226-c38a27441791">

**Comment by cecheta** [comment]
Yes I think it would be better to use an empty string

**Comment by Roopan-Microsoft** [comment]
Its updated and PR (https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1070) is merged, So closing this issue.
