### ISSUE TITLE
setting ORCHESTRATION_STRATEGY to langchain did not seem to be adhered to

### ISSUE THREAD

**Issue by DAVMUNDY** [Azure-Samples/chat-with-your-data-solution-accelerator#56]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> We are deploying this repo with gpt-35-turbo model. We therefore assumed ORCHESTRATION_STRATEGY should be set to langchain. We set that in the ARM template but after we deployed we were getting errors in the front end app and noticed in the admin URL config tab that ORCHESTRATION_STRATEGY was set to OPENAI Functions option. 

### Any log messages given by the failure
>2023-10-23T13:55:28.708618922Z: [ERROR]    File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
2023-10-23T13:55:28.708646822Z: [ERROR]      self._interpret_response_line(
2023-10-23T13:55:28.708655022Z: [ERROR]    File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
2023-10-23T13:55:28.708663323Z: [ERROR]      raise self.handle_error_response(
2023-10-23T13:55:28.708671423Z: [ERROR]  openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

### Expected/desired behavior
> manually changing ORCHESTRATION_STRATEGY in config tab and hitting save fixed issue but maybe someone can check the code

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Thank you for reporting this! We'll review and make any changes to avoid this behavior for other users. Thank you for posting your workaround as well.

**Comment by DeJeremy** [comment]
Hello, the problem comes from the default version being overwrote in the config returned by the `get_active_config_or_default()` function. To fix it, you need to remove the line about the orchestrator (line 207 in `ConfigHelper.py` file for the current main version). The case when the orchestrator is missing from default config is correctly handled in the ConfigHelper init.
