### ISSUE TITLE
The embeddings operation does not work with the specified model, gpt-35-turbo

### ISSUE THREAD

**Issue by shinjiDev** [Azure-Samples/chat-with-your-data-solution-accelerator#57]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Trying to use the .env file with these parameters:
```
AZURE_OPENAI_MODEL=gpt-35-turbo
AZURE_OPENAI_MODEL_NAME=gpt-35-turbo
AZURE_OPENAI_EMBEDDING_MODEL=35
```
### Any log messages given by the failure
>Error message: openai.error.InvalidRequestError: The embeddings operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.
stacktrace:
```
Traceback (most recent call last):
  File "c:\proj\chat-assistant-deployment-data\app.py", line 55, in <module>
    document_processor.process(source_url=file_sas, processors=processors)
  File "c:\proj\chat-assistant-deployment-data\utilities\helpers\DocumentProcessorHelper.py", line 22, in process
    vector_store = vector_store_helper.get_vector_store()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\proj\chat-assistant-deployment-data\utilities\helpers\AzureSearchHelper.py", line 33, in get_vector_store
    vector_search_dimensions=len(llm_helper.get_embedding_model().embed_query("Text")),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cpalomar\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\embeddings\openai.py", line 506, in embed_query
    return self.embed_documents([text])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Expected/desired behavior
> It should work with gpt-35-turbo according to the documentation.

### OS and Version?
> Windows 11

### Mention any other details that might be useful
> Thanks! We'll be in touch soon.

**Comment by ruoccofabrizio** [comment]
Please use text-embedding-ada-002 for embedding generation.
