### ISSUE TITLE
New Deployment Failed - adminweb

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/chat-with-your-data-solution-accelerator#588]
# Describe the bug

New deployment failed upon executing azd up. The adminweb was not there in the resource group.

# Expected behavior

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. Run azd up
2. See error:

Deploying services (azd deploy)

  (x) Failed: Deploying service adminweb

ERROR: getting target resource: resource not found: unable to find a resource tagged with 'azd-service-name: adminweb'. Ensure the service resource is correctly tagged in your infrastructure configuration, and rerun provision

ERROR: error executing step command 'deploy --all': getting target resource: resource not found: unable to find a resource tagged with 'azd-service-name: adminweb'. Ensure the service resource is correctly tagged in your infrastructure configuration, and rerun provision

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by superhindupur** [comment]
Thanks for the bug report @mirojs. Can you check your .azure/<env-name>/.env file and tell me what the value of the AZURE_APP_SERVICE_HOSTING_MODEL variable is?

**Comment by superhindupur** [comment]
Ok, if you're deploying from your clone of the repo, please follow the instructions at https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/LOCAL_DEPLOYMENT.md. 

Specifically, you need to run 

```
azd env set AZURE_APP_SERVICE_HOSTING_MODEL code
```

before azd up.

**Comment by superhindupur** [comment]
@mirojs can you confirm whether that fixed your problem?

**Comment by mirojs** [comment]
@superhindupur For the previous deployed one, after using azd down -> azd up, it worked again. 
For brand new deployment, it would prompt 
"ERROR: listing accounts: listing subscriptions: failed to load subscriptions from tenant 'Default Directory' : reauthentication required, run `azd auth login --scope https://management.azure.com//.default` to log in; failed to load subscriptions from tenant '---' : reauthentication required, run `azd auth login --scope https://management.azure.com//.default` to log in". And the reauthentication didn't work.

**Comment by mirojs** [comment]
@superhindupur For the previous deployed one, after using azd down -> azd up, there's an error "ERROR - Container web-...-admin_... for site web-...-admin has exited, failing site start
"

**Comment by mirojs** [comment]
@superhindupur Managed For brand new deployment, azd auth logout -> azd auth login -> azd up -> ERROR: error executing step command 'package --all': failed packaging service 'adminweb': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '127', Path: '/tmp/azd-prepackage-1333944515.sh'. : exit code: 127, stdout: , stderr: /tmp/azd-prepackage-1333944515.sh: 5: poetry: not found

**Comment by superhindupur** [comment]
Looks like you might not be running with a devcontainer. Are you following the steps at https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/LOCAL_DEPLOYMENT.md exactly?

**Comment by mirojs** [comment]
@superhindupur Sorry, I git clone from the  repo first and then followed step 4  to 6 in the link since I need a private repo for the following code update

**Comment by superhindupur** [comment]
Ok,. Are you using VSCode? You will need to install the DevContainers extension for VSCode and open the Chat With Your Data project inside a DevContainer (https://code.visualstudio.com/docs/devcontainers/containers#_quick-start-open-an-existing-folder-in-a-container). Then you can follow https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/LOCAL_DEPLOYMENT.md from step 4.

**Comment by mirojs** [comment]
@superhindupur I'm not using VSCode but I could give it a try if that a must. In the meanwhile, how should the public repo update be synced and merged smoothly in that case?

**Comment by superhindupur** [comment]
There's another option. If you aren't using VSCode (and therefore can't use the devcontainers extension), follow https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docs/NON_DEVCONTAINER_SETUP.md

You can ignore the VSCode section, but install all the other mentioned tools. In your error message, you were missing 'poetry', which you will need to install (https://python-poetry.org/docs/)

**Comment by mirojs** [comment]
@superhindupur It's deploying! One poetry away, thanks a million!

BTW, for one previous deployed App (git clone -->azd up), which was broken (container apps shown in resource group) following the public repo update, I did azd down --purge --> azd env set AZURE_APP_SERVICE_HOSTING_MODEL code --> azd up last night and the deployment went through but adminweb app could not be started now with "ERROR - Container web-...-admin_... for site web-...-admin has exited, failing site start".

Any clue why container was mentioned in the error message? Anything else I could do to clean up further without starting over everything from the very beginning? Thanks.

**Comment by mirojs** [comment]
@superhindupur After deploying for a 3rd time, it started to work by itself. Not sure why. And thanks for the help!

**Comment by mirojs** [comment]
@ross-p-smith please, thanks for the help!
