### ISSUE TITLE
Restructure code within this repo to make it modularized.

### ISSUE THREAD

**Issue by superhindupur** [Azure-Samples/chat-with-your-data-solution-accelerator#590]
# Motivation

There are several refactors needed within this repo to remove duplication of code, achieve separation of concerns and split out classes that are doing too many things. 
The repo also does not make it very clear about which directories belong to what components (e.g. backend/ folder contains code called by the frontend API, the function app and the admin wesbite).
This issue is planned to parent all of the issues that fall under the umbrella of repo restructuring for clarity. 

# How would you feel if this feature request was implemented?

![zen](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHJ3N25sYjI2Y2Y0YW5haWlyMGg2am1rdmRycTV4cXRteXk4eWVwdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/zhRA0okWxTGiu78uSk/giphy.gif)

# Requirements

No specific requirements - we will mark this issue as done when all tasks are completed.

# Tasks

- [x] #916
- [ ] #541 
- [x] #917
- [ ] #515 
- [ ] #625 
- [x] #601
- [x] #558

**Comment by ross-p-smith** [comment]
Closing this issue and labelled the subtasks as Good First Issue for people to pick up
