### ISSUE TITLE
Issue when run locally

### ISSUE THREAD

**Issue by Renwanlan** [Azure-Samples/chat-with-your-data-solution-accelerator#60]
I have a error when I start to chat with the bot I run locally. Please help me fix the error if you know why. Thank you!
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/37434917/12198516-7b33-4f74-9d47-6d0412bc14e0)

**Comment by gmndrg** [comment]
Hello @Renwanlan that looks related to calling the Content Safety API. 
@ruoccofabrizio can you please help us taking a quick look next week for guidance? Thanks!

**Comment by ruoccofabrizio** [comment]
Please check you have the following env variables pointing to a Content Safety endpoint or disable the Content filter in the Admin panel.

'AZURE_CONTENT_SAFETY_ENDPOINT'
'AZURE_CONTENT_SAFETY_KEY'
