### ISSUE TITLE
Move imports to top of files

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#601]
# Motivation

There are a number of imports which are done within functions, rather than at the top of the file, such as [here](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/256522ff8b5d10adadfe827079171dbc66ab8804/code/create_app.py#L219).

These include latency into requests in the application, as the modules should be imported during application startup not during API requests.

# How would you feel if this feature request was implemented?

![image](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWFjZTByZzF3ZWRrMWF5OHdjb3poZ3hnZjJ5ZmQxeTY0cXJyaGFrNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/mdfPpglf2c0QxED151/giphy.gif)

# Requirements

A list of requirements to consider this feature delivered
- Move all imports (except instrumentation imports) to the top of files

# Tasks

_To be filled in by the engineer picking up the issue_

**Comment by liammoat** [comment]
Would be happy to pick this up 👍  @ross-p-smith
