### ISSUE TITLE
OpenAI Eeror

### ISSUE THREAD

**Issue by nhtkid** [Azure-Samples/chat-with-your-data-solution-accelerator#63]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I completed the deployment, get to the web app front end. When I plugged in a public website to ingest, I received an OpenAI API error.

### Any log messages given by the failure
>( openai.error.AuthenticationError: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

### Expected/desired behavior
>a successful data ingestion

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
I created my models in Azure OpenAI studio and copied the API key there.
It was provided prior to the template deployment in the API field.
My question is now if I need to check or change to a different API key, where do I find it?
Which resources actually has the API key and how do I modify it?
Thanks.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
All the created Web apps and Azure Functions (under their environment variables in the portal):
•	admin web app
•	web app
•	backend function
