### ISSUE TITLE
Suppress verbose traces in Application Insights 

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#636]
# Motivation

In Application Insights there are very verbose Info logs coming from the Azure libraries which are filling up the traces, making it hard to find real application logs.

![Screenshot 2024-04-09 103103](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/60179183/6b8fd0ba-3d42-4fe5-9a91-622c9c347ab0)

According to this [comment](https://github.com/microsoft/ApplicationInsights-Python/issues/317#issuecomment-1742051140), they can be suppressed.

```py
logging.getLogger("azure.core.pipeline.policies.http_logging_policy").setLevel(logging.WARNING)
logging.getLogger("azure.monitor.opentelemetry.exporter.export").setLevel(logging.WARNING)
```

# How would you feel if this feature request was implemented?

_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

# Requirements

A list of requirements to consider this feature delivered
- Remove verbose logging from App Insights

# Tasks

_To be filled in by the engineer picking up the issue_

**Comment by macieyng** [comment]
See this comment by @lzchen https://github.com/Azure/azure-functions-python-worker/issues/1342#issuecomment-2050153573

Also, see my repo with examples: https://github.com/macieyng/otel-examples - open an issue there if you need some support, we'll figure out something 😉
