### ISSUE TITLE
Remove TokenLogger

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#638]
# Motivation

The `TokenLogger` class is not necessary, now that App Insights has been integrated into the application properly. As a result, the class can be removed, and replaced with using a normal `logger`. The env var `APPINSIGHTS_CONNECTION_STRING` can also be removed completely from the application.

# Requirements

A list of requirements to consider this feature delivered
- Remove `TokenLogger`
- Ensure that tokens are still logged (Note: INFO logs are currently not shown #637 )
- Remove all references to `APPINSIGHTS_CONNECTION_STRING`

# Tasks

_To be filled in by the engineer picking up the issue_

**Comment by liammoat** [comment]
Happy to pick this up 👍 @ross-p-smith
