### ISSUE TITLE
() Invalid expression: Could not find a property named 'content' on type 'search.document'. Parameter name: $select Code: Message: Invalid expression: Could not find a property named 'content' on type 'search.document'. Parameter name: $select

### ISSUE THREAD

**Issue by KdwMatsuda** [Azure-Samples/chat-with-your-data-solution-accelerator#64]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Please provide more details, hopefully with screenshots, what are you trying to do when you get that error and have you uploaded your documents already? Does your index has any data?
