### ISSUE TITLE
Prompt is not reflected in chat after updating in admin app. 

### ISSUE THREAD

**Issue by ketanvh** [Azure-Samples/chat-with-your-data-solution-accelerator#643]
# Describe the bug
I updated the prompt in Admin Portal. I can see same has been updated in storage account. But chat app doesnt take the latest prompt. Also the stream log doesnt show anything.

# Expected behavior
Chat app should use updated prompt and show same in stream log (of web service in azure) in debug.

# Debugging information

## Steps to reproduce
1. Go to '.Admin portal'
2. Click on 'config'
3.  Add new prompot
4. Same configuration
5. Restart Chat webapp (so it may reflect changes)
6. Ask question
7. Check the stream log or answer

**Comment by cecheta** [comment]
Hello @ketanvh , I have just tried this but was not able to reproduce the issue. I modified the prompt by including "Test" and I can see this in the storage account and also in the logs.

![Screenshot 2024-04-10 110355](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/60179183/f1b5a15e-ddc2-482f-b5bb-4343f81cc18f)
![Screenshot 2024-04-10 110430](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/60179183/293019fb-ab20-4030-85e3-68da2445658e)
![Screenshot 2024-04-10 110538](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/60179183/6c1293b1-2fa8-4b51-aa3c-4da4bf1b737c)

Please could you send similar screenshots showing the prompt in the Admin app, the contents of the config file in the storage account, and also the prompt from the App Service logs showing the prompt that is used when calling the LLM? Feel free to partially redact information as necessary.
