### ISSUE TITLE
issue when test chat : The API deployment for this resource does not exist. If you created..

### ISSUE THREAD

**Issue by TIDIALLO** [Azure-Samples/chat-with-your-data-solution-accelerator#65]
Hi,

I was implementing the chat-with-your-data-solution-accelerator solution, but I get an error during the chat test.
description of the error:

 

/api/conversation/custom:1

Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)

 

{
"error": "415 Unsupported Media Type: Did not attempt to load JSON data because the request Content-Type was not 'application/json'."
}

**Comment by gmndrg** [comment]
Hello @TIDIALLO can you please provide all of your repro steps to understand when you get that error?

**Comment by TIDIALLO** [comment]
I resumed the implementation on the azure side by following all steps and everything went well until deployment but the problem is if I start the test on the chat it generates the error, it does not even answer the greeting (for example hi)

**Comment by gmndrg** [comment]
Have you uploaded any files so you can start asking questions about your content? What kind of files have you uploaded to the index via the admin portal?

**Comment by TIDIALLO** [comment]
yes I loaded the ones on the doc folder in my storage account in a container via the admin interface (which I found cool with streamlit

**Comment by gmndrg** [comment]
Unfortunately, this looks related to perhaps some (or one of the files you uploaded). Unless you upload your documents online so we can check what may be the issue to assist (which is not recommended unless public), there is not much guidance we can provide for this.

**Comment by krohm** [comment]
Hi i'm also hitting a 500 when calling the api/conversation/custom, with {"error":"Invalid connection string"}
Environment Variables and Key are looking good

**Comment by gmndrg** [comment]
@krohm one of your environment variables for a connection string has to be incorrect since that is a product error, not a repo error.

**Comment by krohm** [comment]
Hi, it was the APPINSIGHTS_CONNECTION_STRING setting which was missing ... :-(

**Comment by TIDIALLO** [comment]
Hi @krohm, I would like to know if you did the implementation locally or directly in azure?
thanks in advance

**Comment by krohm** [comment]
Hi @TIDIALLO , i have done the whole stuff in Azure, but have not used the bicep, instead of this i have written down all the neccessary components in Terraform

**Comment by gmndrg** [comment]
Like mentioned above without being able to repro everything, unfortunately we cannot repro, since this looks like a specific error when using the deployment you have, We can only recommend to redeploy the whole solution from scratch and try uploading a doc, try to repro, and until you get the error, perhaps you're able to identify if related to an unsupported doc or similar.

**Comment by TIDIALLO** [comment]
okay,
I’ll star the solution again and see it all go well, 😉it’s weird 
Thank you

**Comment by TIDIALLO** [comment]
@gmndrg is there a possibility to make an inspection deu code a part of azure

**Comment by gmndrg** [comment]
Hello @TIDIALLO custom code review is not part of the support, unfortunately. We try to help with documentation and general guidance accordingly.

**Comment by TIDIALLO** [comment]
![ai3](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/47597738/91a8a65a-d779-4392-b8ca-621824bddd07)
 this is my last erro

**Comment by gmndrg** [comment]
Please review this post to see if the suggestions help: https://learn.microsoft.com/en-us/answers/questions/1401622/azure-openai-issue-with-endpoint-connection-errno. If you still face the issues after checking DNS and if you're not using a proxy, then please help opening a support case with the Azure OpenAI team for assistance: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request Thanks.

**Comment by gmndrg** [comment]
@daniheck-msft If you're facing the same issues with chat with your data as well, it might be related to your Azure OpenAI on your data. Please open a support ticket in the portal to engage the Azure OpenAI team: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
