### ISSUE TITLE
Add versioning to project

### ISSUE THREAD

**Issue by adamdougal** [Azure-Samples/chat-with-your-data-solution-accelerator#651]
# Motivation

We should add versioning to this project along with a changelog to enable users to easily see what's changed between deployments.

This will also allow us to make breaking changes by doing major version bumps, along with adding migration guides in the changelog.

# How would you feel if this feature request was implemented?

![changes](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2txMWw3bTRjeWJyeXliYnNpazg0M3F3MWZ6cHA0ZzBzdHliYTE4NyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3rgXBGYrye5vSfhMdO/giphy.gif)

# Requirements

- Automated versioning and GitHub release when merges to main
- Documentation on how to do major version changes
- Automated changelog generation

# Tasks

- [ ] #805 
- [x] #829 
- [x] #832
- [x] #837
- [x] #838
- [x] #859
- [ ] #907
- [ ] #909
- [ ] #910

**Comment by cecheta** [comment]
Changed repo settings:

* Only squash merging is allowed
* Commit message will always default to PR title

Raised #859 to make check mandatory
