### ISSUE TITLE
Request for updating ReadMe.md file

### ISSUE THREAD

**Issue by komalg1** [Azure-Samples/chat-with-your-data-solution-accelerator#66]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Getting an error when running `docker compose up` on **WSL**

### Any log messages given by the failure
> Failed to load /home/alias/chat-with-your-data-solution-accelerator/docker/..\.env: open /home/alias/chat-with-your-data-solution-accelerator/docker/..\.env: no such file or directory.

### Expected/desired behavior
>

### OS and Version?
> Linux (Ubuntu)

### Versions
>

### Mention any other details that might be useful
Issue is the way it's setting the path to that .env file. here
https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/main/docker/docker-compose.yml#L9
. It's using backslash \ which will only work on Windows. We need to modify the docker-compose.yml to use forward slash / .

It would be great if this can be updated in the ReadMe.md file. It would also be great if we could add a autodetect feature where the type of slash to be used is autodetected based on the OS version
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
@komalg1 this has been added to the documentation. Thank you so much for raising this and the solution. We'll consider for future improvements. Thank you!
