### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by ross-p-smith** [Azure-Samples/chat-with-your-data-solution-accelerator#69]
Improve the developer experience. As a developer I would like to clone the repository and be able to deploy this accelerator from my machine and run everything locally with the minimum of ceremony.
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

- [x] #70
- [x] #96
- [x] #130
- [x] #141
- [x] #262
- [x] #341
- [x] #209 
- [ ] #340

from a single command. (Happy to take ownership of this btw!)

**Comment by gmndrg** [comment]
Thanks a lot for your contribution!

**Comment by ross-p-smith** [comment]
Dependent on #281
