### ISSUE TITLE
User chat webpage error 

### ISSUE THREAD

**Issue by SGafur** [Azure-Samples/chat-with-your-data-solution-accelerator#690]
# Describe the bug
When the user asks a question, they receive an error in the browser but there isn't much information in the logs to help debug.

# Expected behavior

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. Go to this repo and do the one click deployment. Use GPT-4-1106 model and region UK South: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/tree/main
2. After successfully deployment and user uploads their documents, when posting a question, their browser showed this error -  
4. See error below 

## Screenshots
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/74244259/32145567-2dc9-4054-bd3c-849389673711)
![MicrosoftTeams-image (1)](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/74244259/245ab7b1-50a0-4248-a80b-4a2c2ecf1578)

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by cecheta** [comment]
After looking into this more deeply, we determined that the error was due to a timeout. Fixed by #694
