### ISSUE TITLE
Local Debug Failing - Can't find Streamlit or Flask Modules

### ISSUE THREAD

**Issue by cmw2** [Azure-Samples/chat-with-your-data-solution-accelerator#699]
# Describe the bug
Using the VS Code debug options to launch the app components is failing.  When launching the Admin site get message: "No module named streamlit".  When launching Frontend (api) get message: "No module named flask"

# Expected behavior
Expect the launch commands to work and be in debug mode in VS Code.

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information

## Steps to reproduce
1. Clone code into WSL (I'm on windows machine)
3. Open via "code ." in WSL
4. Reopen in container
5. azd auth / up (and 2nd deploy of azd deploy adminweb as discussed in another issue to get it working)
6. Go to debug tab in vscode, and try "Launch Admin Site".  Also try "Launch Frontend (api).  (Launch Frontend (UI) works but it fails since the api isn't running.)

## Screenshots
<img width="1904" alt="image" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/3027065/4079ee49-3453-47af-b141-1b3b919125eb">

## Logs

If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
Hi Chris, I have actually seen this before. I don't suppose you used that button "Open in DevContainers" in the Local Setup instructions? I think that does something weird for Windows machines. I think I need to update those instructions if you did!
 - Open WSL and navigate to a linux directory not a Windows /mnt/c location
 - clone
 - Open with `code .`
 - before you get to `azd up` if `flask` doesn't work in a Terminal in your devcontainer - we have that to fix first!

Happy to share screen at some point if you like

**Comment by cecheta** [comment]
Hi @cmw2, could you try the following:

* In VS Code, press F1 to open the Command Palette
* Enter `Python: Select Interpreter`
* Ensure that the Virtual Environment from Poetry is selected. It will have a name like `chat-with-your-data-solution-accelerator-PQGzWDPx-py3.11`
* Try again

**Comment by cmw2** [comment]
That was it.  I should have caught that, doh!
