### ISSUE TITLE
scripts/package_frontend.sh causes build error because of Windows-style CRLF line endings (^M)

### ISSUE THREAD

**Issue by alsiesta** [Azure-Samples/chat-with-your-data-solution-accelerator#742]
# Describe the bug
The script "package_frontend.sh" contains Windows-style CRLF line endings (^M), which causes issues when running the scripts in a UNIX/Linux environment like the Dev. Container

# Fix
I ran the following command on the package_frontend.sh: 
sed -i 's/\r$//' package_frontend.sh

# Debugging information
Run app in Dev Container

## Steps to reproduce
1. Build Dev. Container
2. Run azd up
3. Packaging service web failes

## Logs
```
vscode ➜ /workspaces/chat-with-your-data-solution-accelerator $ azd up

Packaging services (azd package)

  (✓) Done: Packaging service adminweb
  - Package Output: /tmp/chat-with-your-data-solution-accelerator-adminweb-azddeploy-1713871762.zip

  (✓) Done: Packaging service function
  - Package Output: /tmp/chat-with-your-data-solution-accelerator-function-azddeploy-1713871794.zip

  |       | Packaging service web/usr/bin/env: ‘bash\r’: No such file or directory
  (x) Failed: Packaging service web

ERROR: failed packaging service 'web': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '127', Path: '../scripts/package_frontend.sh'. : exit code: 127

ERROR: error executing step command 'package --all': failed packaging service 'web': failed invoking event handlers for 'prepackage', 'prepackage' hook failed with exit code: '127', Path: '../scripts/package_frontend.sh'. : exit code: 127
```
If applicable, add logs to help the engineer debug the problem.

---

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
Hi @alsiesta I've checked my version along with a colleague and both of ours are set to `LF`. I'm wondering - could it be a setting in your VSCode?

What is this value on your machine?
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/6254153/7a495d41-ce0a-4773-a1bb-800b1d3d9f91)
