### ISSUE TITLE
Update the Index for Conversation log to match the same index

### ISSUE THREAD

**Issue by komalg1** [Azure-Samples/chat-with-your-data-solution-accelerator#754]
Required by #321 
# Description

TBD

# Tasks

_To be filled in by the engineer picking up the subtask

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by superhindupur** [comment]
I have tested that the coversation index structure is the same with and without integrated vectorization. 

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/1787601/420c3711-189e-49a4-939d-e74ebdfbc5f5)

So there is no work needed under this issue. Closing.
