### ISSUE TITLE
Addition of "Delete Data" Page in Admin WebApp

### ISSUE THREAD

**Issue by cpich3g** [Azure-Samples/chat-with-your-data-solution-accelerator#77]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
>
An option to add a delete data section within the Admin app to remove documents that have been indexed previously or by mistake during testing.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Merged and this functionality was included
