### ISSUE TITLE
Unable to deploy the accelerator due to old application insights

### ISSUE THREAD

**Issue by gaurav12de** [Azure-Samples/chat-with-your-data-solution-accelerator#83]
Hi, 
This solution accelerator is using application insights which is not allowed by my organization.
Is there anyway to edit the repo or template and provide the components which we already have in our system?

**Comment by josegrivera** [comment]
I also have the same problem.....Insights moved from Classic to workspace with Log Analytics....and I can't create Classic Insights anymore.....is there a way to change that on the Template itself?

**Comment by gmndrg** [comment]
This PR solves this issue: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/76
If Application Insights can't be used, you need to fork the repo and remove from the template on your end.
Closing accordingly.
