### ISSUE TITLE
Add Chat History 

### ISSUE THREAD

**Issue by Carcamo-ben** [Azure-Samples/chat-with-your-data-solution-accelerator#85]
# Motivation

There is a chat history like the AOAI bring your own data deployment. This allows users to leave the session and return later and retain their previous chat.

# How would you feel if this feature request was implemented?

![slaps](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTczNHdnamxwdmNzMzR3Ym8wdm16eDczcXQxanVpeDd5Zmo2MWpmMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Y4ySj5vECPfQ9IgoS6/giphy.gif)

# Requirements

- Design how to best persist the chat history
- Chat history should be persisted for a user

**To be decided:**
- How long does the chat need to be persisted for?
- How do we link a chat history to a user?

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by hunterjam** [comment]
@ruoccofabrizio @gmndrg --- We also flagged this as a missing feature. Want to add this to our agenda when we meet again in January for V2 discussions?

**Comment by gmndrg** [comment]
Hi @hunterjam we have the list of features with priorities that will be reviewed within our team and to discuss after the Holidays and this is definitely part of this list! Thank you so much for flagging this!

**Comment by jasonpnnl** [comment]
We would like to +1 this feature request.

Aside from that it seems very promising as a base for us to build RAG chat applications on.

**Comment by RubenHaisma** [comment]
We would also like to see this. Thanks. Bye.

**Comment by ross-p-smith** [comment]
Implemented in #1288
