### ISSUE TITLE
Error: `No module named 'utilities'`

### ISSUE THREAD

**Issue by charris-msft** [Azure-Samples/chat-with-your-data-solution-accelerator#87]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. In Azure Portal, open chatsa01-website-admin > Environment variables
> 2. Change value for `AZURE_OPENAI_RESOURCE` from "https://charris-openai4.openai.azure.com/" to "charris-openai4"
> 3. Refresh Explore Data page
> 4. Receive errors below
> 5 . Change the value back
> 6. Continue to receive errors
> 7. Restart web app
> 8. Continue to receive errors
> 9. Navigate back to Admin page (no errors)
> 10. Navigate to Explore Data page **No Errors**

### Any log messages given by the failure
> ModuleNotFoundError: No module named 'utilities'
Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
File "/usr/local/src/myscripts/admin/pages/01_Ingest_Data.py", line 14, in <module>
    from utilities.helpers.ConfigHelper import ConfigHelper

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/74415662/7dede061-1c77-48be-a9fc-8bbd80a6be12)

### Expected/desired behavior
> the config value can be corrected without breaking the app.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JC324-cam** [comment]
Hi, I deployed this service a few weeks ago, and there was no problem. However I got the same error message when I deployed its service last Friday after the template field changed.

My procedure is below
1. Deploy to Azure with the custom template and go to the Admin website to upload files
2. Get file uploaded successfully message but did not find it on the Explore Data page
3. Can find it under the container of my storage account 
4. Checked the website and got this error message on the development tool 
![Screenshot 2023-12-06 at 09 54 47](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/136442402/b89d305f-ff16-43ed-9e40-f7ad9842cd7f)
5. after a few mins, I got the same error message 
![Screenshot 2023-12-06 at 11 00 56](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/136442402/0172caae-9449-4fe6-8936-9ae2a9c229eb)

**Comment by adamdougal** [comment]
I've been able to reproduce this by just:
1. Navigating to the `Explore Data` page
2. Restarting the webapp
3. Refresing the page

I was then able to simply "resolve" it by navigating to the home page and then returning.

**Comment by adamdougal** [comment]
So it seems setting the `PYTHONPATH` env var to `/usr/local/src` fixes the issue. @charris-msft can you try that and confirm?

I've made a change to the Dockerfile here https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/112
