### ISSUE TITLE
Citations for URLs should include full URL including domain

### ISSUE THREAD

**Issue by charris-msft** [Azure-Samples/chat-with-your-data-solution-accelerator#88]
# Motivation

Citations should be clickable to enable users to quickly see full references.

## Minimal steps to reproduce
> 1. Use the Admin site to ingest a URL (https://legislature.idaho.gov/statutesrules/idstat/Title25/T25CH28/SECT25-2801/)
> 2. Ask a question that can be satisfied by the URL content (Who can make an order requiring dog owners to get a license?)
> 3. Click the Citation button in the response
> 4. Notice that the citation does *not* include the domain of the website

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/74415662/52451ddb-d0c8-4bbc-b4ad-08add83d56b8)

# Requirements

- Citations should have a full clickable link including domain

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by ross-p-smith** [comment]
This might actually be complete - just needs validation (I think)

**Comment by komalg1** [comment]
Although the citations page is not showing the full domain, it is clickable and redirects to the web page successfully. Same has been handled for Integrated Vectorization
