### ISSUE TITLE
Deploy to Azure Template Broken

### ISSUE THREAD

**Issue by hunterjam** [Azure-Samples/chat-with-your-data-solution-accelerator#89]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. From the README, select "Deploy to Azure"
> 1. The "Form Recognizer Location" is empty (this used to be auto-populated with the Location variable)
> 1. Enter the required fields and select "Next"
> 1. Error: Validation failed. View error details.

### Any log messages given by the failure
> {"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource 'StorageAccountName' at line '264' and column '27' is not valid: Unable to evaluate the template language function 'substring'. The index and length parameters must refer to a location within the string. The index parameter: '0', the length parameter: '24', the length of the string parameter: '22'. Please see https://aka.ms/arm-function-substring for usage details.. Please see https://aka.ms/arm-functions for usage details.'."}

### Expected/desired behavior
> Validation should be successful. 

### OS and Version?
> Windows 11

### Versions
> This issue occurs using the most recent PR #76 

### Mention any other details that might be useful
![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/31451884/fb385e49-c3e2-40a3-85fb-e2b37ccca979)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
This is fixed as part of PR [#91](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/91)
