### ISSUE TITLE
Deploy To Azure button, the backend app service deployment cannot get the clientKey

### ISSUE THREAD

**Issue by Fr4nc3** [Azure-Samples/chat-with-your-data-solution-accelerator#924]
# Describe the bug
when you build the demo, which uses containers pre-built from the main branch by using the deploy to azure blue button. The built template process fails.  

# Expected behavior
when you build the demo, which uses containers pre-built from the main branch by using the deploy to azure blue button. The built template should build without error.

# How does this bug make you feel?
_Share a gif from [giphy](https://giphy.com/) to tells us how you'd feel_

---

# Debugging information
You go to the 
## Steps to reproduce

1. Go to CWYD readme page.
2. Click on Deploy to Azure
3. Go to Azure Template in Azure portal
5.  Press create
6. Deployment failed 
7. Error Message 

## Screenshots
{

  "Code": "BadRequest",

  "Message": "Encountered an error (InternalServerError) from host runtime.",

  "Target": null,

  "Details": [

    {

      "Message": "Encountered an error (InternalServerError) from host runtime."

    },

    {

      "Code": "BadRequest"

    },

    {

      "ErrorEntity": {

        "Code": "BadRequest",

        "Message": "Encountered an error (InternalServerError) from host runtime."

      }

    }

  ],

  "Innererror": null

} (Code: BadRequest, Target: /subscriptions/xxxx/resourceGroups/rg-francia/providers/Microsoft.Web/sites/backend-xxxx-docker/host/default/functionKeys/clientKey)

**Comment by ross-p-smith** [comment]
Checked with @Fr4nc3 - now working - Many thanks for raising this!
