### ISSUE TITLE
`test_raises_exception_if_bad_response_code` test fails intermittently

### ISSUE THREAD

**Issue by cecheta** [Azure-Samples/chat-with-your-data-solution-accelerator#962]
# Describe the bug
The `test_raises_exception_if_bad_response_code` test in `code/tests/utilities/helpers/test_azure_computer_vision_client.py` fails intermittently. The exact cause of the error cannot be determined from the logs, as a new exception is raised when it occurs.

# Expected behavior
All tests should pass consistently.

---

# Debugging information

## Screenshots

![image](https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/60179183/37e6883e-bdc0-4db1-862e-d271fe817ca5)

## Logs

If applicable, add logs to help the engineer debug the problem.

```
FAILED code/tests/utilities/helpers/test_azure_computer_vision_client.py::test_raises_exception_if_bad_response_code - assert 'Call to Azur...Vision failed' == 'Call to Azur...r says no"\n}'
  
  + Call to Azure Computer Vision failed
  - Call to Azure Computer Vision failed with status: 500, body: {
  -     "error": "computer says no"
  - }
```

---

# Tasks

_To be filled in by the engineer picking up the issue_

**Comment by cecheta** [comment]
I have managed to reproduce this by increasing the self-defined timeout in the previous test `test_vectorize_image_calls_computer_vision_timeout`.

It seems like the `time.sleep()` imposed in the previous request leaks into the subsequent tests, so the `0.25s` is then hit

**Comment by Roopan-Microsoft** [comment]
Hi @cecheta - I see the there are no failures recently for the above mentioned Tests. Please let me know if you still face issues.

**Comment by cecheta** [comment]
There was a failure last Monday 3rd June, has there been a fix since then?

https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/actions/runs/9353896745

**Comment by Roopan-Microsoft** [comment]
Hey @cecheta - Sorry for the delayed response. Just got some time to check this issue. I think if we change the order of execution of the test cases and move that particular test case at the bottom it seems working fine with more sleep time. Can we provide that fix for now? What do you think?

**Comment by cecheta** [comment]
Hi @Roopan-Microsoft , personally I think that having to change the order of tests in order to make one pass seems like a code smell, instead I would investigate if there is any other way that this scenario can be tested, or remove the test with the sleep all together.

However, I am no longer actively working on this repo, therefore feel free to fix this as you see fit 🙂

**Comment by Pavan-Microsoft** [comment]
> Hi @Roopan-Microsoft , personally I think that having to change the order of tests in order to make one pass seems like a code smell, instead I would investigate if there is any other way that this scenario can be tested, or remove the test with the sleep all together.
> 
> However, I am no longer actively working on this repo, therefore feel free to fix this as you see fit 🙂

@cecheta Thank you for your feedback. We agree that changing the order of tests to make one pass is not ideal. Therefore, we have removed the use of **time.sleep(0.3)** in the **test_vectorize_image_calls_computer_vision_timeout** test and used a mock request in the test. We will monitor the test case to ensure it runs consistently. @Roopan-Microsoft 
[https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/pull/1127](url)

**Comment by Roopan-Microsoft** [comment]
Closing this issue for now and will re-open in case if any failure in future. Thanks.
