### ISSUE TITLE
Add gpt-4o support

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/chat-with-your-data-solution-accelerator#967]
# Motivation

A clear and concise description of why this feature would be useful and the value it would bring.
Explain any alternatives considered and why they are not sufficient.

gpt-4o is wonderful. Could we implement that soon, thanks?

# How would you feel if this feature request was implemented?

![alt_text](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMTdxcnlrZjYzMzMwY3NkeXFqY2U3MjhtdG8xcHhna3ZxbHY5YngzayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3zstvx1ldHJOky2W8L/giphy.gif)_

# Requirements

A list of requirements to consider this feature delivered
- Requirement 1
- Requirement 2
- ...

# Tasks

_To be filled in by the engineer picking up the issue_

- [ ] Task 1
- [ ] Task 2
- [ ] ...

**Comment by guilhermelia** [comment]
I think there is no big changes needed to implement this features. You need only change your deployment model on Azure OpenAI Services and change his name on Enviroment Variables of the Web apps.

**Comment by mirojs** [comment]
That may not be the case beyond the texts.
