### ISSUE TITLE
What version of Python is required for this project to run locally?

### ISSUE THREAD

**Issue by johntallon** [Azure-Samples/chat-with-your-data-solution-accelerator#99]
> I am having issues when I try in enter a prompt and the app is trying to call the conversation/custom api. Just get a HTTP 500 server error. What version of Python is required for this project to run locally?

- [x] documentation issue or request

### Minimal steps to reproduce
> I am just following the local dev/debug install and run in the readme. 

<img width="536" alt="image" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/10197455/4d70ff97-dc6a-4ee7-96ce-6a1cf3187d42">

> Running this with VSCode and Windows 11

**Comment by adamdougal** [comment]
I'd recommened 3.11
